--
-- PostgreSQL database dump
--

\restrict 7p8dBNEiGGklxWnsfhSCsSZNNga9FcrOCOuSsPo7qGv9hgGv1KI60iqZdrHHCxs

-- Dumped from database version 17.10
-- Dumped by pg_dump version 17.10

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: character_class; Type: TABLE; Schema: public; Owner: jdr
--

CREATE TABLE public.character_class (
    id integer NOT NULL,
    slug character varying(80) NOT NULL,
    name character varying(120) NOT NULL,
    hit_die integer NOT NULL,
    subclass_selection_level integer NOT NULL,
    spellcasting_progression character varying(255) NOT NULL,
    description text,
    custom boolean NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    updated_at timestamp(0) without time zone NOT NULL
);


ALTER TABLE public.character_class OWNER TO jdr;

--
-- Name: character_class_id_seq; Type: SEQUENCE; Schema: public; Owner: jdr
--

ALTER TABLE public.character_class ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.character_class_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: character_feature_definition; Type: TABLE; Schema: public; Owner: jdr
--

CREATE TABLE public.character_feature_definition (
    id integer NOT NULL,
    slug character varying(100) NOT NULL,
    name character varying(150) NOT NULL,
    description text,
    activation_type character varying(255) NOT NULL,
    visible boolean DEFAULT true NOT NULL,
    custom boolean NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    updated_at timestamp(0) without time zone NOT NULL,
    resource_definition_id integer
);


ALTER TABLE public.character_feature_definition OWNER TO jdr;

--
-- Name: character_feature_definition_id_seq; Type: SEQUENCE; Schema: public; Owner: jdr
--

ALTER TABLE public.character_feature_definition ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.character_feature_definition_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: character_feature_rule; Type: TABLE; Schema: public; Owner: jdr
--

CREATE TABLE public.character_feature_rule (
    id integer NOT NULL,
    unlock_level integer NOT NULL,
    display_order integer DEFAULT 0 NOT NULL,
    feature_definition_id integer NOT NULL,
    character_class_id integer,
    character_subclass_id integer,
    character_race_id integer,
    feat_id integer
);


ALTER TABLE public.character_feature_rule OWNER TO jdr;

--
-- Name: character_feature_rule_id_seq; Type: SEQUENCE; Schema: public; Owner: jdr
--

ALTER TABLE public.character_feature_rule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.character_feature_rule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: character_subclass; Type: TABLE; Schema: public; Owner: jdr
--

CREATE TABLE public.character_subclass (
    id integer NOT NULL,
    slug character varying(80) NOT NULL,
    name character varying(120) NOT NULL,
    spellcasting_progression character varying(255) DEFAULT NULL::character varying,
    description text,
    custom boolean NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    updated_at timestamp(0) without time zone NOT NULL,
    character_class_id integer NOT NULL
);


ALTER TABLE public.character_subclass OWNER TO jdr;

--
-- Name: character_subclass_id_seq; Type: SEQUENCE; Schema: public; Owner: jdr
--

ALTER TABLE public.character_subclass ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.character_subclass_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: trackable_resource_definition; Type: TABLE; Schema: public; Owner: jdr
--

CREATE TABLE public.trackable_resource_definition (
    id integer NOT NULL,
    slug character varying(100) NOT NULL,
    name character varying(150) NOT NULL,
    description text,
    recharge_type character varying(255) NOT NULL,
    maximum_type character varying(255) NOT NULL,
    base_maximum integer NOT NULL,
    multiplier integer NOT NULL,
    minimum_maximum integer NOT NULL,
    scaling_ability character varying(255) DEFAULT NULL::character varying,
    custom boolean NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    updated_at timestamp(0) without time zone NOT NULL
);


ALTER TABLE public.trackable_resource_definition OWNER TO jdr;

--
-- Name: trackable_resource_definition_id_seq; Type: SEQUENCE; Schema: public; Owner: jdr
--

ALTER TABLE public.trackable_resource_definition ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.trackable_resource_definition_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: trackable_resource_rule; Type: TABLE; Schema: public; Owner: jdr
--

CREATE TABLE public.trackable_resource_rule (
    id integer NOT NULL,
    unlock_level integer NOT NULL,
    maximum_override integer,
    resource_definition_id integer NOT NULL,
    character_class_id integer,
    character_subclass_id integer,
    character_race_id integer,
    feat_id integer
);


ALTER TABLE public.trackable_resource_rule OWNER TO jdr;

--
-- Name: trackable_resource_rule_id_seq; Type: SEQUENCE; Schema: public; Owner: jdr
--

ALTER TABLE public.trackable_resource_rule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.trackable_resource_rule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: character_class character_class_pkey; Type: CONSTRAINT; Schema: public; Owner: jdr
--

ALTER TABLE ONLY public.character_class
    ADD CONSTRAINT character_class_pkey PRIMARY KEY (id);


--
-- Name: character_feature_definition character_feature_definition_pkey; Type: CONSTRAINT; Schema: public; Owner: jdr
--

ALTER TABLE ONLY public.character_feature_definition
    ADD CONSTRAINT character_feature_definition_pkey PRIMARY KEY (id);


--
-- Name: character_feature_rule character_feature_rule_pkey; Type: CONSTRAINT; Schema: public; Owner: jdr
--

ALTER TABLE ONLY public.character_feature_rule
    ADD CONSTRAINT character_feature_rule_pkey PRIMARY KEY (id);


--
-- Name: character_subclass character_subclass_pkey; Type: CONSTRAINT; Schema: public; Owner: jdr
--

ALTER TABLE ONLY public.character_subclass
    ADD CONSTRAINT character_subclass_pkey PRIMARY KEY (id);


--
-- Name: trackable_resource_definition trackable_resource_definition_pkey; Type: CONSTRAINT; Schema: public; Owner: jdr
--

ALTER TABLE ONLY public.trackable_resource_definition
    ADD CONSTRAINT trackable_resource_definition_pkey PRIMARY KEY (id);


--
-- Name: trackable_resource_rule trackable_resource_rule_pkey; Type: CONSTRAINT; Schema: public; Owner: jdr
--

ALTER TABLE ONLY public.trackable_resource_rule
    ADD CONSTRAINT trackable_resource_rule_pkey PRIMARY KEY (id);


--
-- Name: idx_12ebb15998f28fd7; Type: INDEX; Schema: public; Owner: jdr
--

CREATE INDEX idx_12ebb15998f28fd7 ON public.character_feature_definition USING btree (resource_definition_id);


--
-- Name: idx_7b7b5a467fc5430; Type: INDEX; Schema: public; Owner: jdr
--

CREATE INDEX idx_7b7b5a467fc5430 ON public.trackable_resource_rule USING btree (character_race_id);


--
-- Name: idx_7b7b5a4698f28fd7; Type: INDEX; Schema: public; Owner: jdr
--

CREATE INDEX idx_7b7b5a4698f28fd7 ON public.trackable_resource_rule USING btree (resource_definition_id);


--
-- Name: idx_7b7b5a46b201e281; Type: INDEX; Schema: public; Owner: jdr
--

CREATE INDEX idx_7b7b5a46b201e281 ON public.trackable_resource_rule USING btree (character_class_id);


--
-- Name: idx_7b7b5a46e5fa1c35; Type: INDEX; Schema: public; Owner: jdr
--

CREATE INDEX idx_7b7b5a46e5fa1c35 ON public.trackable_resource_rule USING btree (character_subclass_id);


--
-- Name: idx_7b7b5a46f43c4d5c; Type: INDEX; Schema: public; Owner: jdr
--

CREATE INDEX idx_7b7b5a46f43c4d5c ON public.trackable_resource_rule USING btree (feat_id);


--
-- Name: idx_cb96a6d67fc5430; Type: INDEX; Schema: public; Owner: jdr
--

CREATE INDEX idx_cb96a6d67fc5430 ON public.character_feature_rule USING btree (character_race_id);


--
-- Name: idx_cb96a6d6b201e281; Type: INDEX; Schema: public; Owner: jdr
--

CREATE INDEX idx_cb96a6d6b201e281 ON public.character_feature_rule USING btree (character_class_id);


--
-- Name: idx_cb96a6d6b8a00e59; Type: INDEX; Schema: public; Owner: jdr
--

CREATE INDEX idx_cb96a6d6b8a00e59 ON public.character_feature_rule USING btree (feature_definition_id);


--
-- Name: idx_cb96a6d6e5fa1c35; Type: INDEX; Schema: public; Owner: jdr
--

CREATE INDEX idx_cb96a6d6e5fa1c35 ON public.character_feature_rule USING btree (character_subclass_id);


--
-- Name: idx_cb96a6d6f43c4d5c; Type: INDEX; Schema: public; Owner: jdr
--

CREATE INDEX idx_cb96a6d6f43c4d5c ON public.character_feature_rule USING btree (feat_id);


--
-- Name: idx_cff91fd4b201e281; Type: INDEX; Schema: public; Owner: jdr
--

CREATE INDEX idx_cff91fd4b201e281 ON public.character_subclass USING btree (character_class_id);


--
-- Name: uniq_character_class_slug; Type: INDEX; Schema: public; Owner: jdr
--

CREATE UNIQUE INDEX uniq_character_class_slug ON public.character_class USING btree (slug);


--
-- Name: uniq_character_feature_slug; Type: INDEX; Schema: public; Owner: jdr
--

CREATE UNIQUE INDEX uniq_character_feature_slug ON public.character_feature_definition USING btree (slug);


--
-- Name: uniq_class_feature_level; Type: INDEX; Schema: public; Owner: jdr
--

CREATE UNIQUE INDEX uniq_class_feature_level ON public.character_feature_rule USING btree (character_class_id, feature_definition_id, unlock_level);


--
-- Name: uniq_class_resource_level; Type: INDEX; Schema: public; Owner: jdr
--

CREATE UNIQUE INDEX uniq_class_resource_level ON public.trackable_resource_rule USING btree (character_class_id, resource_definition_id, unlock_level);


--
-- Name: uniq_feat_feature_level; Type: INDEX; Schema: public; Owner: jdr
--

CREATE UNIQUE INDEX uniq_feat_feature_level ON public.character_feature_rule USING btree (feat_id, feature_definition_id, unlock_level);


--
-- Name: uniq_feat_resource_level; Type: INDEX; Schema: public; Owner: jdr
--

CREATE UNIQUE INDEX uniq_feat_resource_level ON public.trackable_resource_rule USING btree (feat_id, resource_definition_id, unlock_level);


--
-- Name: uniq_race_feature_level; Type: INDEX; Schema: public; Owner: jdr
--

CREATE UNIQUE INDEX uniq_race_feature_level ON public.character_feature_rule USING btree (character_race_id, feature_definition_id, unlock_level);


--
-- Name: uniq_race_resource_level; Type: INDEX; Schema: public; Owner: jdr
--

CREATE UNIQUE INDEX uniq_race_resource_level ON public.trackable_resource_rule USING btree (character_race_id, resource_definition_id, unlock_level);


--
-- Name: uniq_subclass_class_slug; Type: INDEX; Schema: public; Owner: jdr
--

CREATE UNIQUE INDEX uniq_subclass_class_slug ON public.character_subclass USING btree (character_class_id, slug);


--
-- Name: uniq_subclass_feature_level; Type: INDEX; Schema: public; Owner: jdr
--

CREATE UNIQUE INDEX uniq_subclass_feature_level ON public.character_feature_rule USING btree (character_subclass_id, feature_definition_id, unlock_level);


--
-- Name: uniq_subclass_resource_level; Type: INDEX; Schema: public; Owner: jdr
--

CREATE UNIQUE INDEX uniq_subclass_resource_level ON public.trackable_resource_rule USING btree (character_subclass_id, resource_definition_id, unlock_level);


--
-- Name: uniq_trackable_resource_slug; Type: INDEX; Schema: public; Owner: jdr
--

CREATE UNIQUE INDEX uniq_trackable_resource_slug ON public.trackable_resource_definition USING btree (slug);


--
-- Name: character_feature_definition fk_12ebb15998f28fd7; Type: FK CONSTRAINT; Schema: public; Owner: jdr
--

ALTER TABLE ONLY public.character_feature_definition
    ADD CONSTRAINT fk_12ebb15998f28fd7 FOREIGN KEY (resource_definition_id) REFERENCES public.trackable_resource_definition(id) ON DELETE SET NULL;


--
-- Name: trackable_resource_rule fk_7b7b5a467fc5430; Type: FK CONSTRAINT; Schema: public; Owner: jdr
--

ALTER TABLE ONLY public.trackable_resource_rule
    ADD CONSTRAINT fk_7b7b5a467fc5430 FOREIGN KEY (character_race_id) REFERENCES public.character_race(id) ON DELETE CASCADE;


--
-- Name: trackable_resource_rule fk_7b7b5a4698f28fd7; Type: FK CONSTRAINT; Schema: public; Owner: jdr
--

ALTER TABLE ONLY public.trackable_resource_rule
    ADD CONSTRAINT fk_7b7b5a4698f28fd7 FOREIGN KEY (resource_definition_id) REFERENCES public.trackable_resource_definition(id) ON DELETE CASCADE;


--
-- Name: trackable_resource_rule fk_7b7b5a46b201e281; Type: FK CONSTRAINT; Schema: public; Owner: jdr
--

ALTER TABLE ONLY public.trackable_resource_rule
    ADD CONSTRAINT fk_7b7b5a46b201e281 FOREIGN KEY (character_class_id) REFERENCES public.character_class(id) ON DELETE CASCADE;


--
-- Name: trackable_resource_rule fk_7b7b5a46e5fa1c35; Type: FK CONSTRAINT; Schema: public; Owner: jdr
--

ALTER TABLE ONLY public.trackable_resource_rule
    ADD CONSTRAINT fk_7b7b5a46e5fa1c35 FOREIGN KEY (character_subclass_id) REFERENCES public.character_subclass(id) ON DELETE CASCADE;


--
-- Name: trackable_resource_rule fk_7b7b5a46f43c4d5c; Type: FK CONSTRAINT; Schema: public; Owner: jdr
--

ALTER TABLE ONLY public.trackable_resource_rule
    ADD CONSTRAINT fk_7b7b5a46f43c4d5c FOREIGN KEY (feat_id) REFERENCES public.feat(id) ON DELETE CASCADE;


--
-- Name: character_feature_rule fk_cb96a6d67fc5430; Type: FK CONSTRAINT; Schema: public; Owner: jdr
--

ALTER TABLE ONLY public.character_feature_rule
    ADD CONSTRAINT fk_cb96a6d67fc5430 FOREIGN KEY (character_race_id) REFERENCES public.character_race(id) ON DELETE CASCADE;


--
-- Name: character_feature_rule fk_cb96a6d6b201e281; Type: FK CONSTRAINT; Schema: public; Owner: jdr
--

ALTER TABLE ONLY public.character_feature_rule
    ADD CONSTRAINT fk_cb96a6d6b201e281 FOREIGN KEY (character_class_id) REFERENCES public.character_class(id) ON DELETE CASCADE;


--
-- Name: character_feature_rule fk_cb96a6d6b8a00e59; Type: FK CONSTRAINT; Schema: public; Owner: jdr
--

ALTER TABLE ONLY public.character_feature_rule
    ADD CONSTRAINT fk_cb96a6d6b8a00e59 FOREIGN KEY (feature_definition_id) REFERENCES public.character_feature_definition(id) ON DELETE CASCADE;


--
-- Name: character_feature_rule fk_cb96a6d6e5fa1c35; Type: FK CONSTRAINT; Schema: public; Owner: jdr
--

ALTER TABLE ONLY public.character_feature_rule
    ADD CONSTRAINT fk_cb96a6d6e5fa1c35 FOREIGN KEY (character_subclass_id) REFERENCES public.character_subclass(id) ON DELETE CASCADE;


--
-- Name: character_feature_rule fk_cb96a6d6f43c4d5c; Type: FK CONSTRAINT; Schema: public; Owner: jdr
--

ALTER TABLE ONLY public.character_feature_rule
    ADD CONSTRAINT fk_cb96a6d6f43c4d5c FOREIGN KEY (feat_id) REFERENCES public.feat(id) ON DELETE CASCADE;


--
-- Name: character_subclass fk_cff91fd4b201e281; Type: FK CONSTRAINT; Schema: public; Owner: jdr
--

ALTER TABLE ONLY public.character_subclass
    ADD CONSTRAINT fk_cff91fd4b201e281 FOREIGN KEY (character_class_id) REFERENCES public.character_class(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict 7p8dBNEiGGklxWnsfhSCsSZNNga9FcrOCOuSsPo7qGv9hgGv1KI60iqZdrHHCxs

