--
-- PostgreSQL database dump
--

\restrict B9LmW5o3bJjyJEiAGsaDkkLJjdRtfzg70cPZmVoLkthu40AZWzqdeEPlneVJvJO

-- Dumped from database version 17.10
-- Dumped by pg_dump version 17.10

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: character_class; Type: TABLE DATA; Schema: public; Owner: jdr
--

INSERT INTO public.character_class (id, slug, name, hit_die, subclass_selection_level, spellcasting_progression, description, custom, created_at, updated_at) VALUES (1, 'cleric', 'Clerc', 8, 1, 'full', NULL, false, '2026-09-06 20:41:27', '2026-09-07 15:16:01');
INSERT INTO public.character_class (id, slug, name, hit_die, subclass_selection_level, spellcasting_progression, description, custom, created_at, updated_at) VALUES (2, 'artificer', 'Artificier', 8, 3, 'artificer', NULL, false, '2026-09-06 20:41:27', '2026-09-07 15:16:01');
INSERT INTO public.character_class (id, slug, name, hit_die, subclass_selection_level, spellcasting_progression, description, custom, created_at, updated_at) VALUES (3, 'barbarian', 'Barbare', 12, 3, 'none', NULL, false, '2026-09-06 20:41:27', '2026-09-07 15:16:01');
INSERT INTO public.character_class (id, slug, name, hit_die, subclass_selection_level, spellcasting_progression, description, custom, created_at, updated_at) VALUES (4, 'wizard', 'Magicien', 6, 2, 'full', NULL, false, '2026-09-06 20:41:27', '2026-09-07 15:16:01');
INSERT INTO public.character_class (id, slug, name, hit_die, subclass_selection_level, spellcasting_progression, description, custom, created_at, updated_at) VALUES (5, 'fighter', 'Guerrier', 10, 3, 'none', NULL, false, '2026-09-06 20:41:27', '2026-09-07 15:16:01');
INSERT INTO public.character_class (id, slug, name, hit_die, subclass_selection_level, spellcasting_progression, description, custom, created_at, updated_at) VALUES (6, 'paladin', 'Paladin', 10, 3, 'half', NULL, false, '2026-09-06 20:41:27', '2026-09-07 15:16:01');
INSERT INTO public.character_class (id, slug, name, hit_die, subclass_selection_level, spellcasting_progression, description, custom, created_at, updated_at) VALUES (7, 'rogue', 'Roublard', 8, 3, 'none', NULL, false, '2026-09-06 20:41:27', '2026-09-07 15:16:01');
INSERT INTO public.character_class (id, slug, name, hit_die, subclass_selection_level, spellcasting_progression, description, custom, created_at, updated_at) VALUES (8, 'druide', 'Druide', 8, 2, 'full', NULL, false, '2026-09-08 13:06:02', '2026-09-08 13:08:41');
INSERT INTO public.character_class (id, slug, name, hit_die, subclass_selection_level, spellcasting_progression, description, custom, created_at, updated_at) VALUES (9, 'occultiste', 'Occultiste', 8, 1, 'pact', NULL, false, '2026-09-08 13:09:03', '2026-09-08 13:09:03');
INSERT INTO public.character_class (id, slug, name, hit_die, subclass_selection_level, spellcasting_progression, description, custom, created_at, updated_at) VALUES (10, 'barde', 'Barde', 8, 3, 'full', NULL, false, '2026-09-08 13:09:19', '2026-09-08 13:09:19');
INSERT INTO public.character_class (id, slug, name, hit_die, subclass_selection_level, spellcasting_progression, description, custom, created_at, updated_at) VALUES (11, 'rodeur', 'Rôdeur', 10, 3, 'half', NULL, false, '2026-09-08 13:09:51', '2026-09-08 13:09:51');
INSERT INTO public.character_class (id, slug, name, hit_die, subclass_selection_level, spellcasting_progression, description, custom, created_at, updated_at) VALUES (12, 'sorcerer', 'Ensorceleur', 6, 1, 'full', NULL, false, '2026-09-08 13:10:33', '2026-09-08 13:10:33');
INSERT INTO public.character_class (id, slug, name, hit_die, subclass_selection_level, spellcasting_progression, description, custom, created_at, updated_at) VALUES (13, 'monk', 'Moine', 8, 3, 'none', NULL, false, '2026-09-08 13:11:03', '2026-09-08 13:11:03');


--
-- Data for Name: trackable_resource_definition; Type: TABLE DATA; Schema: public; Owner: jdr
--

INSERT INTO public.trackable_resource_definition (id, slug, name, description, recharge_type, maximum_type, base_maximum, multiplier, minimum_maximum, scaling_ability, custom, created_at, updated_at) VALUES (1, 'rage', 'Rage', NULL, 'long-rest', 'fixed', 2, 1, 0, NULL, false, '2026-09-07 00:31:33', '2026-09-07 15:16:01');
INSERT INTO public.trackable_resource_definition (id, slug, name, description, recharge_type, maximum_type, base_maximum, multiplier, minimum_maximum, scaling_ability, custom, created_at, updated_at) VALUES (2, 'des-de-presage', 'Dés de présage', NULL, 'long-rest', 'fixed', 2, 1, 0, NULL, false, '2026-09-07 18:17:22', '2026-09-07 19:20:49');
INSERT INTO public.trackable_resource_definition (id, slug, name, description, recharge_type, maximum_type, base_maximum, multiplier, minimum_maximum, scaling_ability, custom, created_at, updated_at) VALUES (3, 'utilisations-de-conscience-magique', 'Utilisations de Conscience Magique', NULL, 'long-rest', 'proficiency-bonus', 0, 1, 0, NULL, false, '2026-09-07 22:02:26', '2026-09-07 22:03:18');
INSERT INTO public.trackable_resource_definition (id, slug, name, description, recharge_type, maximum_type, base_maximum, multiplier, minimum_maximum, scaling_ability, custom, created_at, updated_at) VALUES (4, 'utilisations-de-magie-galvanisante', 'Utilisations de Magie galvanisante', NULL, 'long-rest', 'proficiency-bonus', 0, 1, 0, NULL, true, '2026-09-07 22:06:29', '2026-09-07 22:06:29');
INSERT INTO public.trackable_resource_definition (id, slug, name, description, recharge_type, maximum_type, base_maximum, multiplier, minimum_maximum, scaling_ability, custom, created_at, updated_at) VALUES (5, 'utilisation-de-restauration-arcanique', 'Utilisation de Restauration arcanique', NULL, 'long-rest', 'fixed', 1, 1, 1, NULL, false, '2026-09-07 22:30:12', '2026-09-07 22:30:12');
INSERT INTO public.trackable_resource_definition (id, slug, name, description, recharge_type, maximum_type, base_maximum, multiplier, minimum_maximum, scaling_ability, custom, created_at, updated_at) VALUES (6, 'utiisation-du-troisieme-oeil', 'Utiisation du troisième oeil', NULL, 'short-rest', 'fixed', 1, 1, 1, NULL, false, '2026-09-07 22:39:17', '2026-09-07 22:39:17');
INSERT INTO public.trackable_resource_definition (id, slug, name, description, recharge_type, maximum_type, base_maximum, multiplier, minimum_maximum, scaling_ability, custom, created_at, updated_at) VALUES (7, 'utilisation-de-second-souffle', 'Utilisation de second souffle', NULL, 'short-rest', 'fixed', 1, 1, 1, NULL, false, '2026-09-07 23:43:38', '2026-09-07 23:43:38');
INSERT INTO public.trackable_resource_definition (id, slug, name, description, recharge_type, maximum_type, base_maximum, multiplier, minimum_maximum, scaling_ability, custom, created_at, updated_at) VALUES (8, 'utilisation-de-fougue', 'Utilisation de Fougue', NULL, 'short-rest', 'fixed', 1, 1, 1, NULL, false, '2026-09-07 23:45:03', '2026-09-07 23:45:03');
INSERT INTO public.trackable_resource_definition (id, slug, name, description, recharge_type, maximum_type, base_maximum, multiplier, minimum_maximum, scaling_ability, custom, created_at, updated_at) VALUES (9, 'utilisation-de-inflexible', 'Utilisation de Inflexible', NULL, 'long-rest', 'fixed', 1, 1, 1, NULL, false, '2026-09-07 23:46:24', '2026-09-07 23:46:24');
INSERT INTO public.trackable_resource_definition (id, slug, name, description, recharge_type, maximum_type, base_maximum, multiplier, minimum_maximum, scaling_ability, custom, created_at, updated_at) VALUES (10, 'utilisations-d-imposition-des-mains', 'Utilisations d''Imposition des mains', NULL, 'long-rest', 'fixed', 5, 1, 5, NULL, false, '2026-09-08 00:12:13', '2026-09-08 00:12:13');


--
-- Data for Name: character_feature_definition; Type: TABLE DATA; Schema: public; Owner: jdr
--

INSERT INTO public.character_feature_definition (id, slug, name, description, activation_type, visible, custom, created_at, updated_at, resource_definition_id) VALUES (4, 'attaque-temeraire', 'Attaque téméraire', 'Vous pouvez mettre de côté votre défense pour attaquer avec toute la violence du désespoir. Lorsque vous effectuez la première attaque de votre tour, vous pouvez décider d''effectuer une Attaque téméraire. Vous obtenez ainsi un avantage aux jets d''attaque au corps à corps avec une arme utilisant la Force durant ce tour, mais les attaques effectuées contre vous ont également un avantage jusqu''à votre prochain tour.', 'passive', true, false, '2026-09-07 20:06:24', '2026-09-07 20:10:35', NULL);
INSERT INTO public.character_feature_definition (id, slug, name, description, activation_type, visible, custom, created_at, updated_at, resource_definition_id) VALUES (2, 'defense-sans-armure', 'Défense sans armure', 'Tant que vous ne portez pas d''armure, votre classe d''armure est égale à 10 + votre modificateur de Dextérité + votre modificateur de Constitution. Vous pouvez utiliser un bouclier et continuer de profiter de cette capacité.', 'passive', true, false, '2026-09-07 20:05:28', '2026-09-07 20:10:39', NULL);
INSERT INTO public.character_feature_definition (id, slug, name, description, activation_type, visible, custom, created_at, updated_at, resource_definition_id) VALUES (3, 'rage', 'Rage', 'En combat, vous vous battez avec une férocité bestiale. Durant votre tour, vous pouvez entrer en rage en utilisant une action bonus. En rage, vous gagnez les bénéfices suivants si vous ne portez pas d''armure lourde :

Vous avez un avantage aux jets de Force et aux jets de sauvegarde de Force.
Quand vous effectuez une attaque au corps à corps avec une arme utilisant la Force, vous gagnez un bonus aux jets de dégâts qui dépend de votre niveau de barbare, comme indiqué dans la colonne Dégâts de la table ci-dessus.
Vous avez la résistance aux dégâts contondants, perforants et tranchants.
Si vous êtes capable de lancer des sorts, vous ne pouvez les lancer ou vous concentrer sur eux pour toute la durée de la rage.

Votre rage dure 1 minute. Elle finit prématurément si vous devenez inconscient, ou si votre tour se termine et que vous n''avez ni attaqué une créature hostile, ni subi des dégâts, depuis votre précédent tour. Vous pouvez également mettre fin à votre rage durant votre tour par une action bonus. Vous récupérez les utilisations de rage dépensées après avoir terminé un repos long.', 'bonus_action', true, false, '2026-09-07 20:05:55', '2026-09-07 20:10:50', 1);
INSERT INTO public.character_feature_definition (id, slug, name, description, activation_type, visible, custom, created_at, updated_at, resource_definition_id) VALUES (5, 'sens-du-danger', 'Sens du danger', 'Vous ressentez une sensation étrange lorsque les choses qui vous entourent ne sont pas comme elles devraient être, vous donnant un avantage lorsque vous tentez de vous extirper du danger. Vous avez un avantage aux jets de sauvegarde de Dextérité contre les effets que vous pouvez voir, comme les pièges ou les sorts. Pour bénéficier de cet effet vous ne devez pas être aveuglé, assourdi ou incapable d''agir.', 'passive', true, false, '2026-09-07 20:09:57', '2026-09-07 20:10:55', NULL);
INSERT INTO public.character_feature_definition (id, slug, name, description, activation_type, visible, custom, created_at, updated_at, resource_definition_id) VALUES (6, 'attaque-supplementaire', 'Attaque supplémentaire', 'Vous pouvez attaquer deux fois, au lieu d''une seule, chaque fois que vous réalisez l''action Attaquer durant votre tour.', 'passive', true, false, '2026-09-07 20:11:27', '2026-09-07 20:11:27', NULL);
INSERT INTO public.character_feature_definition (id, slug, name, description, activation_type, visible, custom, created_at, updated_at, resource_definition_id) VALUES (7, 'deplacement-rapide', 'Déplacement rapide', 'Votre vitesse augmente de 3 mètres tant que vous ne portez pas d''armure lourde.', 'passive', true, false, '2026-09-07 20:11:45', '2026-09-07 20:11:45', NULL);
INSERT INTO public.character_feature_definition (id, slug, name, description, activation_type, visible, custom, created_at, updated_at, resource_definition_id) VALUES (8, 'instinct-sauvage', 'Instinct sauvage', 'Vos instincts sont si aiguisés que vous obtenez un avantage aux jets d''initiative. De plus, si vous êtes surpris au début du combat et que vous n''êtes pas incapable d''agir, vous pouvez jouer normalement durant votre premier tour, mais seulement si vous entrez en rage avant de faire quoique ce soit d''autre à ce tour.', 'passive', true, false, '2026-09-07 20:12:28', '2026-09-07 20:12:28', NULL);
INSERT INTO public.character_feature_definition (id, slug, name, description, activation_type, visible, custom, created_at, updated_at, resource_definition_id) VALUES (9, 'critique-brutal', 'Critique brutal', 'Vous pouvez lancer un dé de dégâts de votre arme en plus lorsque vous déterminez les dégâts supplémentaires que vous infligez sur un coup critique réussi avec une attaque au corps à corps. Ce bonus aux dégâts passe à deux dés au niveau 13 et à trois dés au niveau 17.', 'passive', true, false, '2026-09-07 20:13:16', '2026-09-07 20:13:16', NULL);
INSERT INTO public.character_feature_definition (id, slug, name, description, activation_type, visible, custom, created_at, updated_at, resource_definition_id) VALUES (10, 'rage-implacable', 'Rage implacable', 'Votre rage vous permet de continuer à combattre en dépit des graves blessures qui vous affectent. Si vous tombez à 0 point de vie pendant votre rage et que vous ne mourrez pas sur le coup, vous pouvez faire un jet de sauvegarde de Constitution DD 10. Si vous le réussissez, vous retournez immédiatement à 1 point de vie. Chaque fois que vous utilisez cette capacité après la première, le DD augmente de 5. Quand vous terminez un repos court ou long le DD retombe à 10.', 'passive', true, false, '2026-09-07 20:17:39', '2026-09-07 20:17:39', NULL);
INSERT INTO public.character_feature_definition (id, slug, name, description, activation_type, visible, custom, created_at, updated_at, resource_definition_id) VALUES (11, 'rage-persistante', 'Rage persistante', 'Votre rage est si intense qu''elle ne s''arrête prématurément qu''à la condition que vous tombiez inconscient ou que vous choisissiez de l''arrêter.', 'passive', true, false, '2026-09-07 20:19:54', '2026-09-07 20:19:54', NULL);
INSERT INTO public.character_feature_definition (id, slug, name, description, activation_type, visible, custom, created_at, updated_at, resource_definition_id) VALUES (12, 'puissance-indomptable', 'Puissance indomptable', 'Si le résultat d''un de vos jets de Force est inférieur à votre valeur de Force, vous pouvez utiliser votre valeur de Force à la place de votre résultat.', 'passive', true, false, '2026-09-07 20:20:47', '2026-09-07 20:20:47', NULL);
INSERT INTO public.character_feature_definition (id, slug, name, description, activation_type, visible, custom, created_at, updated_at, resource_definition_id) VALUES (13, 'champion-primitif', 'Champion primitif', 'Vous êtes l''incarnation de la puissance du monde sauvage. Vos valeurs de Force et de Constitution augmentent de 4. Votre maximum dans ces valeurs de caractéristique est maintenant de 24.', 'passive', true, false, '2026-09-07 20:23:15', '2026-09-07 20:23:15', NULL);
INSERT INTO public.character_feature_definition (id, slug, name, description, activation_type, visible, custom, created_at, updated_at, resource_definition_id) VALUES (14, 'conscience-magique', 'Conscience magique', 'Vous pouvez ouvrir votre conscience à la présence de magie concentrée. Jusqu''à la fin de votre prochain tour, vous connaissez l''emplacement de tout sort ou objet magique dans un rayon de 18 m autour de vous et qui n''est pas caché par un abri total. Lorsque vous sentez un sort, vous reconnaissez à quelle école de magie il appartient. Vous pouvez utiliser cette capacité un nombre de fois égal à votre bonus de maîtrise, et vous récupérez toutes les utilisations dépensées lorsque vous terminez un repos long.', 'action', true, false, '2026-09-07 22:03:11', '2026-09-07 22:03:11', 3);
INSERT INTO public.character_feature_definition (id, slug, name, description, activation_type, visible, custom, created_at, updated_at, resource_definition_id) VALUES (15, 'acces-sauvage', 'Accès sauvage', 'Les énergies magiques qui bouillonnent en vous entrent parfois en éruption. Lorsque vous entrez en rage, consultez la table "Magie Sauvage" pour déterminer au hasard l''effet magique produit. Si l''effet entraîne un jet de sauvegarde, le DD correspondant est égale à 8 + votre bonus de maîtrise + votre modificateur de Constitution.', 'passive', true, false, '2026-09-07 22:05:30', '2026-09-07 22:05:30', NULL);
INSERT INTO public.character_feature_definition (id, slug, name, description, activation_type, visible, custom, created_at, updated_at, resource_definition_id) VALUES (16, 'magie-galvanisante', 'Magie galvanisante', 's pouvez exploiter votre magie sauvage pour vous renforcer ou renforcer un compagnon. Par une action, vous pouvez toucher une créature (y compris vous-même) et lui conférer l''un des avantages suivants de votre choix :

Durant 10 minutes, la créature peut lancer un d3 à chaque fois qu''elle effectue un jet d''attaque ou un jet de caractéristique, et ajouter le nombre obtenu au d20.
Lancez un d3. La créature regagne un emplacement de sort dépensé d''un niveau égal ou inférieur au nombre obtenu (au choix de la créature). Une fois qu''une créature a reçu cet avantage, elle ne peut plus en bénéficier avant d''avoir terminé un repos long.', 'action', true, false, '2026-09-07 22:08:30', '2026-09-07 22:08:30', 4);
INSERT INTO public.character_feature_definition (id, slug, name, description, activation_type, visible, custom, created_at, updated_at, resource_definition_id) VALUES (17, 'riposte-capricieuse', 'Riposte capricieuse', 'Lorsque vous êtes en danger pendant votre rage, votre magie intérieure peut se déchaîner. Immédiatement après avoir subi des dégâts ou échoué à un jet de sauvegarde pendant que vous êtes en rage, vous pouvez utiliser votre réaction pour lancer un dé sur la table de Magie sauvage et l''effet obtenu se produit immédiatement. Cet effet remplace votre effet de Magie sauvage en cours.', 'reaction', true, false, '2026-09-07 22:09:33', '2026-09-07 22:09:33', NULL);
INSERT INTO public.character_feature_definition (id, slug, name, description, activation_type, visible, custom, created_at, updated_at, resource_definition_id) VALUES (18, 'sauvagerie-controlee', 'Sauvagerie contrôlée', 'Chaque fois que vous lancez un dé sur la table de Magie sauvage, vous pouvez lancer le dé deux fois et choisir lequel des deux effets se déclenche. Si vous lancez le même nombre sur les deux dés, vous pouvez ignorer le dé et choisir n''importe quel effet sur la table.', 'passive', true, false, '2026-09-07 22:10:04', '2026-09-07 22:10:04', NULL);
INSERT INTO public.character_feature_definition (id, slug, name, description, activation_type, visible, custom, created_at, updated_at, resource_definition_id) VALUES (19, 'incantation', 'Incantation', NULL, 'passive', true, false, '2026-09-07 22:27:50', '2026-09-07 22:27:50', NULL);
INSERT INTO public.character_feature_definition (id, slug, name, description, activation_type, visible, custom, created_at, updated_at, resource_definition_id) VALUES (20, 'restauration-arcanique', 'Restauration arcanique', 'Vous avez appris à regagner une partie de votre énergie magique par l''étude de votre grimoire. Une fois par jour, lorsque vous terminez un repos court, vous pouvez choisir des emplacements de sorts dépensés à récupérer. Les emplacements de sorts peuvent avoir un niveau combiné égal ou inférieur à la moitié de votre niveau de magicien (arrondi au supérieur), et aucun de ces emplacements ne peut être de niveau 6 ou supérieur.', 'passive', true, false, '2026-09-07 22:30:21', '2026-09-07 22:30:21', 5);
INSERT INTO public.character_feature_definition (id, slug, name, description, activation_type, visible, custom, created_at, updated_at, resource_definition_id) VALUES (21, 'maitrise-des-sorts', 'Maîtrise des sorts', 'Vous avez atteint une telle maîtrise sur certains sorts que vous pouvez les lancer à volonté. Choisissez un sort de magicien de niveau 1 et un sort de magicien de niveau 2 de votre grimoire. Vous pouvez lancer ces sorts à leur niveau le plus bas sans dépenser un emplacement de sort lorsque vous les avez préparés. Si vous voulez lancer l''un de ses sorts à un niveau supérieur, vous devez dépenser un emplacement de sort, de manière normale. En passant 8 heures à étudier, vous pouvez échanger l''un ou les deux sorts que vous avez choisis par d''autres sorts de même niveau.', 'passive', true, false, '2026-09-07 22:31:16', '2026-09-07 22:31:16', NULL);
INSERT INTO public.character_feature_definition (id, slug, name, description, activation_type, visible, custom, created_at, updated_at, resource_definition_id) VALUES (22, 'sorts-de-predilection', 'Sorts de prédilection', 'Vous gagnez la maîtrise de deux sorts puissants et pouvez les lancer avec peu d''effort. Choisissez deux sorts de magicien de niveau 3 de votre grimoire qui seront vos sorts de prédilection. Ces sorts sont toujours préparés, ils ne comptent pas dans le nombre de sorts que vous avez préparé, et vous pouvez lancer chacun d''eux une fois au niveau 3 sans dépenser un emplacement de sort. Une fois un sort lancé de cette manière, vous devez terminer un repos court ou long pour pouvoir le lancer de nouveau. Si vous voulez lancer un de ces sorts à un niveau supérieur, vous devez dépenser un emplacement de sort, de manière normale.', 'passive', true, false, '2026-09-07 22:33:28', '2026-09-07 22:33:28', NULL);
INSERT INTO public.character_feature_definition (id, slug, name, description, activation_type, visible, custom, created_at, updated_at, resource_definition_id) VALUES (23, 'devin-erudit', 'Devin érudit', 'Lorsque vous choisissez cette école, l''or et le temps que vous devez dépenser pour copier un sort de divination dans votre grimoire est divisé par deux.', 'passive', true, false, '2026-09-07 22:35:25', '2026-09-07 22:35:25', NULL);
INSERT INTO public.character_feature_definition (id, slug, name, description, activation_type, visible, custom, created_at, updated_at, resource_definition_id) VALUES (1, 'presage', 'Présage', 'es aperçus du futur commencent à germer dans votre conscience. Lorsque vous terminez un repos long, lancez deux d20 et notez les résultats. Vous pouvez remplacer n''importe quel jet d''attaque, de sauvegarde ou de caractéristique, qu''il soit lancé par vous ou par une créature que vous pouvez voir, par l''un de ces jets anticipés. Vous devez choisir de faire cela avant de lancer le dé, et vous ne pouvez remplacer qu''un seul jet par tour. Chaque jet anticipé ne peut être utilisé qu''une seule fois. Lorsque vous terminez un repos long, vous perdez tous les jets anticipés non-utilisés.', 'passive', true, false, '2026-09-07 19:22:05', '2026-09-07 22:35:47', 2);
INSERT INTO public.character_feature_definition (id, slug, name, description, activation_type, visible, custom, created_at, updated_at, resource_definition_id) VALUES (24, 'divination-experte', 'Divination experte', 'Lancer des sorts de divination vous devient si facile que vous ne dépensez qu''une fraction de vos efforts pour cela. Lorsque vous lancez un sort de divination de niveau 2 ou plus, en utilisant un emplacement de sort, vous récupérez un emplacement de sort dépensé. L''emplacement que vous regagnez doit être d''un niveau inférieur au sort que vous venez de lancer et ne peut pas être d''un niveau supérieur à 5.', 'passive', true, false, '2026-09-07 22:37:57', '2026-09-07 22:37:57', NULL);
INSERT INTO public.character_feature_definition (id, slug, name, description, activation_type, visible, custom, created_at, updated_at, resource_definition_id) VALUES (25, 'troisieme-oeil', 'Troisième oeil', 'Vous pouvez utiliser votre action pour augmenter vos pouvoirs de perception. Dans ce cas, choisissez l''un des avantages suivants, lequel dure jusqu''à ce que vous soyez incapable d''agir ou que vous preniez un repos, court ou long. Vous ne pouvez pas utiliser de nouveau cette capacité jusqu''à ce que vous terminiez un repos.

Compréhension supérieure. Vous pouvez lire toutes les langues.
Vision dans le noir. Vous gagnez vision dans le noir à 18 mètres.
Vision éthérée. Vous pouvez voir dans le plan éthéré dans un rayon de 18 mètres autour de vous.
Voir l''invisible. Vous pouvez voir les créatures et les objets invisibles dans un rayon de 3 mètres autour de vous et dans votre ligne de mire.', 'action', true, false, '2026-09-07 22:39:29', '2026-09-07 22:39:29', 6);
INSERT INTO public.character_feature_definition (id, slug, name, description, activation_type, visible, custom, created_at, updated_at, resource_definition_id) VALUES (26, 'presage-superieur', 'Présage supérieur', 'Les visions de vos rêves s''intensifient et brossent un tableau plus précis dans votre esprit de ce qui va se passer. Vous lancez 3 dés, au lieu de 2, pour votre capacité de Présage.', 'passive', true, false, '2026-09-07 22:40:27', '2026-09-07 22:40:27', NULL);
INSERT INTO public.character_feature_definition (id, slug, name, description, activation_type, visible, custom, created_at, updated_at, resource_definition_id) VALUES (27, 'lien-avec-une-arme', 'Lien avec une arme', 'Vous apprenez un rituel qui crée un lien magique entre vous et une arme. Vous effectuez le rituel pendant 1 heure, ce qui peut être effectué pendant un repos court. L''arme doit être à votre portée tout au long du rituel, à l''issue duquel vous touchez l''arme et forgez le lien. Une fois que vous vous êtes lié avec une arme, vous ne pouvez pas être désarmé de cette arme, sauf si vous êtes incapable d''agir. Si l''arme se trouve sur le même plan d''existence que vous, vous pouvez invoquer cette arme par une action bonus à votre tour, l''amenant à se téléporter instantanément dans votre main. Vous pouvez être lié à un maximum de deux armes, mais ne pouvez en invoquer qu''une seule à la fois avec votre action bonus. Si vous essayez de vous lier à une troisième arme, vous devez rompre le lien avec l''une des deux autres.', 'special', true, false, '2026-09-07 23:36:32', '2026-09-07 23:36:32', NULL);
INSERT INTO public.character_feature_definition (id, slug, name, description, activation_type, visible, custom, created_at, updated_at, resource_definition_id) VALUES (28, 'magie-de-guerre', 'Magie de guerre', 'Lorsque vous utilisez votre action pour lancer un sort mineur, vous pouvez effectuer une attaque avec une arme en tant qu''action bonus.', 'bonus_action', true, false, '2026-09-07 23:37:31', '2026-09-07 23:37:31', NULL);
INSERT INTO public.character_feature_definition (id, slug, name, description, activation_type, visible, custom, created_at, updated_at, resource_definition_id) VALUES (29, 'frappe-occulte', 'Frappe occulte', 'Vous apprenez comment passer la résistance à vos sorts d''une créature, grâce à votre attaque avec une arme. Lorsque vous touchez une créature avec une attaque d''arme, cette créature a un désavantage au prochain jet de sauvegarde contre un sort que vous lancez avant la fin de votre prochain tour.', 'passive', true, false, '2026-09-07 23:38:13', '2026-09-07 23:38:13', NULL);
INSERT INTO public.character_feature_definition (id, slug, name, description, activation_type, visible, custom, created_at, updated_at, resource_definition_id) VALUES (30, 'charge-arcanique', 'Charge arcanique', 'Vous gagnez la capacité de vous téléporter jusqu''à 9 mètres dans un espace inoccupé que vous pouvez voir, lorsque vous utilisez votre Fougue. Vous pouvez vous téléporter avant ou après l''action supplémentaire.', 'passive', true, false, '2026-09-07 23:38:46', '2026-09-07 23:38:46', NULL);
INSERT INTO public.character_feature_definition (id, slug, name, description, activation_type, visible, custom, created_at, updated_at, resource_definition_id) VALUES (31, 'magie-de-guerre-amelioree', 'Magie de guerre améliorée', 'Lorsque vous utilisez votre action pour lancer un sort, vous pouvez effectuez une attaque avec une arme en tant qu''action bonus.', 'bonus_action', true, false, '2026-09-07 23:39:45', '2026-09-07 23:39:45', NULL);
INSERT INTO public.character_feature_definition (id, slug, name, description, activation_type, visible, custom, created_at, updated_at, resource_definition_id) VALUES (32, 'style-de-combat', 'Style de combat', 'Lorsque vous obtenez 1 ou 2 à un dé de dégâts lors d''une attaque que vous effectuez avec une arme de corps à corps que vous tenez avec vos deux mains, vous pouvez relancer le dé et obligatoirement prendre le nouveau résultat, même si celui-ci est un 1 ou un 2. L''arme doit avoir la propriété à deux mains ou polyvalente pour octroyer cet avantage.', 'passive', true, false, '2026-09-07 23:42:15', '2026-09-07 23:42:15', NULL);
INSERT INTO public.character_feature_definition (id, slug, name, description, activation_type, visible, custom, created_at, updated_at, resource_definition_id) VALUES (33, 'second-souffle', 'Second souffle', 'Vous possédez une réserve d''endurance limitée dans laquelle vous pouvez puiser pour vous protéger contre les dégâts. À votre tour vous pouvez utiliser une action bonus pour regagner un nombre de pv égal à 1d10 + votre niveau de guerrier. Une fois cette capacité utilisée, vous devez terminer un repos court ou long pour pouvoir l''utiliser de nouveau.', 'bonus_action', true, false, '2026-09-07 23:44:27', '2026-09-07 23:44:27', 7);
INSERT INTO public.character_feature_definition (id, slug, name, description, activation_type, visible, custom, created_at, updated_at, resource_definition_id) VALUES (34, 'fougue', 'Fougue', 'A votre tour, vous pouvez réaliser une action supplémentaire en plus de votre action normale et de votre éventuelle action bonus. Une fois cette capacité utilisée, vous devez terminer un repos court ou long pour pouvoir l''utiliser de nouveau. À partir du niveau 17, vous pouvez utiliser cette capacité deux fois entre deux repos, mais une seule fois par tour.', 'free_action', true, false, '2026-09-07 23:45:27', '2026-09-07 23:45:27', 8);
INSERT INTO public.character_feature_definition (id, slug, name, description, activation_type, visible, custom, created_at, updated_at, resource_definition_id) VALUES (35, 'inflexible', 'Inflexible', 'Vous pouvez relancer un jet de sauvegarde que vous avez raté. Si vous le faites, vous devez obligatoirement utiliser le nouveau résultat, et ne pouvez pas utiliser de nouveau cette capacité avant d''avoir terminé un repos long. Vous pouvez utiliser cette capacité deux fois entre deux repos longs à partir du niveau 13 et trois fois entre deux repos longs à partir du niveau 17.', 'passive', true, false, '2026-09-07 23:46:30', '2026-09-07 23:46:30', 9);
INSERT INTO public.character_feature_definition (id, slug, name, description, activation_type, visible, custom, created_at, updated_at, resource_definition_id) VALUES (36, 'incantation-chevalier-occulte', 'Incantation — Chevalier occulte', NULL, 'passive', true, false, '2026-09-07 23:52:53', '2026-09-07 23:52:53', NULL);
INSERT INTO public.character_feature_definition (id, slug, name, description, activation_type, visible, custom, created_at, updated_at, resource_definition_id) VALUES (37, 'sens-divin', 'Sens divin', 'Une forte présence maléfique éveille vos sens, comme une odeur nocive, et un bien puissant fait résonner dans vos oreilles une musique céleste. Par une action, vous pouvez éveiller votre conscience pour détecter de telles forces. Jusqu''à la fin de votre prochain tour, vous connaissez l''emplacement de toute créature céleste, fiélon ou mort-vivante dans un rayon de 18 mètres autour de vous, et qui ne se trouve pas derrière un abri total. Vous connaissez le type (céleste, fiélon ou mort-vivant) et le nombre de tous les êtres dont vous sentez la présence, mais pas leur identité (le vampire comte Strahd von Zarovich, par exemple). Dans ce même rayon, vous détectez également la présence d''un lieu ou d''un objet qui a été consacré ou profané, comme avec le sort sanctification.', 'action', true, false, '2026-09-08 00:11:31', '2026-09-08 00:11:31', NULL);
INSERT INTO public.character_feature_definition (id, slug, name, description, activation_type, visible, custom, created_at, updated_at, resource_definition_id) VALUES (38, 'imposition-des-mains', 'Imposition des mains', 'Votre toucher béni peut guérir les blessures. Vous possédez une réserve de points de vie à soigner qui se récupère après chaque repos long. Avec cette réserve, vous pouvez restaurer un nombre total de points de vie égal à votre niveau de paladin multiplié par 5. Au prix d''une action, vous pouvez toucher une créature et puiser dans votre réserve pour soigner autant de points de vie que vous le désirez, sans dépasser le nombre de points dans votre réserve bien entendu.

Vous pouvez également dépenser 5 points de vie de votre réserve pour guérir la cible d''une maladie ou neutraliser un poison qui l''affecte. Vous pouvez soigner plusieurs maladies et neutraliser plusieurs poisons avec une seule imposition des mains en dépensant les points de vie séparément pour chacun d''entre eux. L''imposition des mains n''a pas d''effet sur les morts-vivants et les artificiels.', 'passive', true, false, '2026-09-08 00:12:33', '2026-09-08 00:12:33', 10);
INSERT INTO public.character_feature_definition (id, slug, name, description, activation_type, visible, custom, created_at, updated_at, resource_definition_id) VALUES (39, 'incantation-paladin', 'Incantation - Paladin', 'Vous avez appris à tirer parti de la magie divine à travers la méditation et la prière pour lancer des sorts comme un clerc le ferait.', 'passive', true, false, '2026-09-08 00:13:31', '2026-09-08 00:13:31', NULL);
INSERT INTO public.character_feature_definition (id, slug, name, description, activation_type, visible, custom, created_at, updated_at, resource_definition_id) VALUES (40, 'chatiment-divin', 'Châtiment divin', 'Quand vous touchez une créature avec une arme de corps à corps, vous pouvez utiliser n''importe quel emplacement de sort (de paladin ou autre) pour châtier cette créature et lui infliger des dégâts radiants supplémentaires. Les dégâts supplémentaires infligés sont de 2d8 pour un emplacement de sort de niveau 1, plus 1d8 supplémentaire pour chaque niveau de sort supérieur à 1, jusqu''à un maximum de 5d8. Si la créature est un mort-vivant ou un fiélon, les dégâts augmentent de 1d8, jusqu''à un maximum de 6d8.', 'free_action', true, false, '2026-09-08 00:14:06', '2026-09-08 00:14:06', NULL);
INSERT INTO public.character_feature_definition (id, slug, name, description, activation_type, visible, custom, created_at, updated_at, resource_definition_id) VALUES (41, 'sante-divine', 'Santé divine', 'La magie divine qui coule en vous vous immunise contre les maladies.', 'passive', true, false, '2026-09-08 00:14:18', '2026-09-08 00:14:18', NULL);
INSERT INTO public.character_feature_definition (id, slug, name, description, activation_type, visible, custom, created_at, updated_at, resource_definition_id) VALUES (42, 'aura-de-protection', 'Aura de protection', NULL, 'passive', true, false, '2026-09-08 00:15:30', '2026-09-08 00:15:30', NULL);
INSERT INTO public.character_feature_definition (id, slug, name, description, activation_type, visible, custom, created_at, updated_at, resource_definition_id) VALUES (43, 'aura-de-courage', 'Aura de courage', NULL, 'passive', true, false, '2026-09-08 00:15:40', '2026-09-08 00:15:40', NULL);
INSERT INTO public.character_feature_definition (id, slug, name, description, activation_type, visible, custom, created_at, updated_at, resource_definition_id) VALUES (44, 'chatiment-divin-ameliore', 'Châtiment divin amélioré', 'Vous êtes tellement imprégné de vertus que toutes vos armes de corps à corps portent la puissance divine en elles. Lorsque vous touchez avec une arme de corps à corps, la créature cible subit 1d8 dégâts radiants supplémentaires.', 'passive', true, false, '2026-09-08 00:15:59', '2026-09-08 00:15:59', NULL);
INSERT INTO public.character_feature_definition (id, slug, name, description, activation_type, visible, custom, created_at, updated_at, resource_definition_id) VALUES (45, 'contact-purifiant', 'Contact purifiant', 'Vous pouvez utiliser votre action pour mettre fin à un sort sur vous ou une créature consentante que vous touchez. Vous pouvez utiliser cette capacité un nombre de fois égal à votre modificateur de Charisme (minimum 1) entre deux repos long.', 'passive', true, false, '2026-09-08 00:16:26', '2026-09-08 00:16:26', NULL);


--
-- Data for Name: character_subclass; Type: TABLE DATA; Schema: public; Owner: jdr
--

INSERT INTO public.character_subclass (id, slug, name, spellcasting_progression, description, custom, created_at, updated_at, character_class_id) VALUES (1, 'light-domain', 'Domaine de la Lumière', NULL, NULL, false, '2026-09-06 20:41:28', '2026-09-07 15:16:02', 1);
INSERT INTO public.character_subclass (id, slug, name, spellcasting_progression, description, custom, created_at, updated_at, character_class_id) VALUES (2, 'artillerist', 'Artilleur', NULL, NULL, false, '2026-09-06 20:41:28', '2026-09-07 15:16:02', 2);
INSERT INTO public.character_subclass (id, slug, name, spellcasting_progression, description, custom, created_at, updated_at, character_class_id) VALUES (3, 'wild-magic', 'Magie sauvage', NULL, NULL, false, '2026-09-06 20:41:28', '2026-09-07 15:16:02', 3);
INSERT INTO public.character_subclass (id, slug, name, spellcasting_progression, description, custom, created_at, updated_at, character_class_id) VALUES (5, 'eldritch-knight', 'Chevalier occulte', 'third', NULL, false, '2026-09-06 20:41:28', '2026-09-07 15:16:02', 5);
INSERT INTO public.character_subclass (id, slug, name, spellcasting_progression, description, custom, created_at, updated_at, character_class_id) VALUES (7, 'chantelame', 'Chantelâme', 'full', NULL, false, '2026-09-07 22:15:18', '2026-09-07 22:15:18', 4);
INSERT INTO public.character_subclass (id, slug, name, spellcasting_progression, description, custom, created_at, updated_at, character_class_id) VALUES (4, 'divination', 'Divination', 'full', NULL, false, '2026-09-06 20:41:28', '2026-09-07 22:27:23', 4);
INSERT INTO public.character_subclass (id, slug, name, spellcasting_progression, description, custom, created_at, updated_at, character_class_id) VALUES (8, 'chevalier-occulte', 'Chevalier occulte 2', NULL, NULL, false, '2026-09-07 23:35:18', '2026-09-07 23:48:53', 5);
INSERT INTO public.character_subclass (id, slug, name, spellcasting_progression, description, custom, created_at, updated_at, character_class_id) VALUES (6, 'vengeance', 'Serment de Vengeance', 'half', NULL, false, '2026-09-06 20:41:28', '2026-09-08 00:18:55', 6);


--
-- Data for Name: character_feature_rule; Type: TABLE DATA; Schema: public; Owner: jdr
--

INSERT INTO public.character_feature_rule (id, unlock_level, display_order, feature_definition_id, character_class_id, character_subclass_id, character_race_id, feat_id) VALUES (2, 5, 0, 6, 3, NULL, NULL, NULL);
INSERT INTO public.character_feature_rule (id, unlock_level, display_order, feature_definition_id, character_class_id, character_subclass_id, character_race_id, feat_id) VALUES (3, 2, 0, 4, 3, NULL, NULL, NULL);
INSERT INTO public.character_feature_rule (id, unlock_level, display_order, feature_definition_id, character_class_id, character_subclass_id, character_race_id, feat_id) VALUES (4, 20, 0, 13, 3, NULL, NULL, NULL);
INSERT INTO public.character_feature_rule (id, unlock_level, display_order, feature_definition_id, character_class_id, character_subclass_id, character_race_id, feat_id) VALUES (5, 9, 0, 9, 3, NULL, NULL, NULL);
INSERT INTO public.character_feature_rule (id, unlock_level, display_order, feature_definition_id, character_class_id, character_subclass_id, character_race_id, feat_id) VALUES (6, 2, 0, 2, 3, NULL, NULL, NULL);
INSERT INTO public.character_feature_rule (id, unlock_level, display_order, feature_definition_id, character_class_id, character_subclass_id, character_race_id, feat_id) VALUES (7, 5, 0, 7, 3, NULL, NULL, NULL);
INSERT INTO public.character_feature_rule (id, unlock_level, display_order, feature_definition_id, character_class_id, character_subclass_id, character_race_id, feat_id) VALUES (8, 7, 0, 8, 3, NULL, NULL, NULL);
INSERT INTO public.character_feature_rule (id, unlock_level, display_order, feature_definition_id, character_class_id, character_subclass_id, character_race_id, feat_id) VALUES (9, 18, 0, 12, 3, NULL, NULL, NULL);
INSERT INTO public.character_feature_rule (id, unlock_level, display_order, feature_definition_id, character_class_id, character_subclass_id, character_race_id, feat_id) VALUES (10, 1, 0, 3, 3, NULL, NULL, NULL);
INSERT INTO public.character_feature_rule (id, unlock_level, display_order, feature_definition_id, character_class_id, character_subclass_id, character_race_id, feat_id) VALUES (11, 11, 0, 10, 3, NULL, NULL, NULL);
INSERT INTO public.character_feature_rule (id, unlock_level, display_order, feature_definition_id, character_class_id, character_subclass_id, character_race_id, feat_id) VALUES (12, 15, 0, 11, 3, NULL, NULL, NULL);
INSERT INTO public.character_feature_rule (id, unlock_level, display_order, feature_definition_id, character_class_id, character_subclass_id, character_race_id, feat_id) VALUES (13, 3, 0, 15, NULL, 3, NULL, NULL);
INSERT INTO public.character_feature_rule (id, unlock_level, display_order, feature_definition_id, character_class_id, character_subclass_id, character_race_id, feat_id) VALUES (14, 3, 0, 14, NULL, 3, NULL, NULL);
INSERT INTO public.character_feature_rule (id, unlock_level, display_order, feature_definition_id, character_class_id, character_subclass_id, character_race_id, feat_id) VALUES (15, 6, 0, 16, NULL, 3, NULL, NULL);
INSERT INTO public.character_feature_rule (id, unlock_level, display_order, feature_definition_id, character_class_id, character_subclass_id, character_race_id, feat_id) VALUES (16, 10, 0, 17, NULL, 3, NULL, NULL);
INSERT INTO public.character_feature_rule (id, unlock_level, display_order, feature_definition_id, character_class_id, character_subclass_id, character_race_id, feat_id) VALUES (17, 14, 0, 18, NULL, 3, NULL, NULL);
INSERT INTO public.character_feature_rule (id, unlock_level, display_order, feature_definition_id, character_class_id, character_subclass_id, character_race_id, feat_id) VALUES (36, 3, 3, 36, NULL, 5, NULL, NULL);
INSERT INTO public.character_feature_rule (id, unlock_level, display_order, feature_definition_id, character_class_id, character_subclass_id, character_race_id, feat_id) VALUES (31, 3, 3, 27, NULL, 5, NULL, NULL);
INSERT INTO public.character_feature_rule (id, unlock_level, display_order, feature_definition_id, character_class_id, character_subclass_id, character_race_id, feat_id) VALUES (32, 7, 7, 28, NULL, 5, NULL, NULL);
INSERT INTO public.character_feature_rule (id, unlock_level, display_order, feature_definition_id, character_class_id, character_subclass_id, character_race_id, feat_id) VALUES (33, 10, 10, 29, NULL, 5, NULL, NULL);
INSERT INTO public.character_feature_rule (id, unlock_level, display_order, feature_definition_id, character_class_id, character_subclass_id, character_race_id, feat_id) VALUES (35, 18, 18, 31, NULL, 5, NULL, NULL);
INSERT INTO public.character_feature_rule (id, unlock_level, display_order, feature_definition_id, character_class_id, character_subclass_id, character_race_id, feat_id) VALUES (34, 15, 15, 30, NULL, 5, NULL, NULL);
INSERT INTO public.character_feature_rule (id, unlock_level, display_order, feature_definition_id, character_class_id, character_subclass_id, character_race_id, feat_id) VALUES (30, 1, 1, 32, 5, NULL, NULL, NULL);
INSERT INTO public.character_feature_rule (id, unlock_level, display_order, feature_definition_id, character_class_id, character_subclass_id, character_race_id, feat_id) VALUES (28, 2, 2, 34, 5, NULL, NULL, NULL);
INSERT INTO public.character_feature_rule (id, unlock_level, display_order, feature_definition_id, character_class_id, character_subclass_id, character_race_id, feat_id) VALUES (29, 2, 2, 33, 5, NULL, NULL, NULL);
INSERT INTO public.character_feature_rule (id, unlock_level, display_order, feature_definition_id, character_class_id, character_subclass_id, character_race_id, feat_id) VALUES (27, 5, 5, 6, 5, NULL, NULL, NULL);
INSERT INTO public.character_feature_rule (id, unlock_level, display_order, feature_definition_id, character_class_id, character_subclass_id, character_race_id, feat_id) VALUES (26, 9, 9, 35, 5, NULL, NULL, NULL);
INSERT INTO public.character_feature_rule (id, unlock_level, display_order, feature_definition_id, character_class_id, character_subclass_id, character_race_id, feat_id) VALUES (21, 1, 1, 19, 4, NULL, NULL, NULL);
INSERT INTO public.character_feature_rule (id, unlock_level, display_order, feature_definition_id, character_class_id, character_subclass_id, character_race_id, feat_id) VALUES (20, 1, 1, 20, 4, NULL, NULL, NULL);
INSERT INTO public.character_feature_rule (id, unlock_level, display_order, feature_definition_id, character_class_id, character_subclass_id, character_race_id, feat_id) VALUES (18, 18, 18, 21, 4, NULL, NULL, NULL);
INSERT INTO public.character_feature_rule (id, unlock_level, display_order, feature_definition_id, character_class_id, character_subclass_id, character_race_id, feat_id) VALUES (19, 20, 20, 22, 4, NULL, NULL, NULL);
INSERT INTO public.character_feature_rule (id, unlock_level, display_order, feature_definition_id, character_class_id, character_subclass_id, character_race_id, feat_id) VALUES (25, 2, 2, 23, NULL, 4, NULL, NULL);
INSERT INTO public.character_feature_rule (id, unlock_level, display_order, feature_definition_id, character_class_id, character_subclass_id, character_race_id, feat_id) VALUES (1, 2, 2, 1, NULL, 4, NULL, NULL);
INSERT INTO public.character_feature_rule (id, unlock_level, display_order, feature_definition_id, character_class_id, character_subclass_id, character_race_id, feat_id) VALUES (24, 6, 6, 24, NULL, 4, NULL, NULL);
INSERT INTO public.character_feature_rule (id, unlock_level, display_order, feature_definition_id, character_class_id, character_subclass_id, character_race_id, feat_id) VALUES (23, 10, 10, 25, NULL, 4, NULL, NULL);
INSERT INTO public.character_feature_rule (id, unlock_level, display_order, feature_definition_id, character_class_id, character_subclass_id, character_race_id, feat_id) VALUES (22, 14, 14, 26, NULL, 4, NULL, NULL);


--
-- Data for Name: trackable_resource_rule; Type: TABLE DATA; Schema: public; Owner: jdr
--

INSERT INTO public.trackable_resource_rule (id, unlock_level, maximum_override, resource_definition_id, character_class_id, character_subclass_id, character_race_id, feat_id) VALUES (1, 1, 2, 1, 3, NULL, NULL, NULL);
INSERT INTO public.trackable_resource_rule (id, unlock_level, maximum_override, resource_definition_id, character_class_id, character_subclass_id, character_race_id, feat_id) VALUES (2, 3, 3, 1, 3, NULL, NULL, NULL);
INSERT INTO public.trackable_resource_rule (id, unlock_level, maximum_override, resource_definition_id, character_class_id, character_subclass_id, character_race_id, feat_id) VALUES (3, 6, 4, 1, 3, NULL, NULL, NULL);
INSERT INTO public.trackable_resource_rule (id, unlock_level, maximum_override, resource_definition_id, character_class_id, character_subclass_id, character_race_id, feat_id) VALUES (4, 12, 5, 1, 3, NULL, NULL, NULL);
INSERT INTO public.trackable_resource_rule (id, unlock_level, maximum_override, resource_definition_id, character_class_id, character_subclass_id, character_race_id, feat_id) VALUES (5, 17, 6, 1, 3, NULL, NULL, NULL);


--
-- Name: character_class_id_seq; Type: SEQUENCE SET; Schema: public; Owner: jdr
--

SELECT pg_catalog.setval('public.character_class_id_seq', 13, true);


--
-- Name: character_feature_definition_id_seq; Type: SEQUENCE SET; Schema: public; Owner: jdr
--

SELECT pg_catalog.setval('public.character_feature_definition_id_seq', 45, true);


--
-- Name: character_feature_rule_id_seq; Type: SEQUENCE SET; Schema: public; Owner: jdr
--

SELECT pg_catalog.setval('public.character_feature_rule_id_seq', 36, true);


--
-- Name: character_subclass_id_seq; Type: SEQUENCE SET; Schema: public; Owner: jdr
--

SELECT pg_catalog.setval('public.character_subclass_id_seq', 8, true);


--
-- Name: trackable_resource_definition_id_seq; Type: SEQUENCE SET; Schema: public; Owner: jdr
--

SELECT pg_catalog.setval('public.trackable_resource_definition_id_seq', 10, true);


--
-- Name: trackable_resource_rule_id_seq; Type: SEQUENCE SET; Schema: public; Owner: jdr
--

SELECT pg_catalog.setval('public.trackable_resource_rule_id_seq', 5, true);


--
-- PostgreSQL database dump complete
--

\unrestrict B9LmW5o3bJjyJEiAGsaDkkLJjdRtfzg70cPZmVoLkthu40AZWzqdeEPlneVJvJO

