--
-- PostgreSQL database dump
--

\restrict 8DedF4PA4nrjDovOLzlxSRLdl5qbXXejXveya9K1PaQd1Xsm1cHkmz2OPJzmVq9

-- Dumped from database version 17.10
-- Dumped by pg_dump version 17.10

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: character_race; Type: TABLE; Schema: public; Owner: jdr
--

CREATE TABLE public.character_race (
    id integer NOT NULL,
    slug character varying(80) NOT NULL,
    name character varying(120) NOT NULL,
    description text,
    custom boolean NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    updated_at timestamp(0) without time zone NOT NULL,
    parent_race_id integer,
    feat_choice_count integer DEFAULT 0 NOT NULL
);


ALTER TABLE public.character_race OWNER TO jdr;

--
-- Name: character_race_id_seq; Type: SEQUENCE; Schema: public; Owner: jdr
--

ALTER TABLE public.character_race ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.character_race_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: race_ability_modifier; Type: TABLE; Schema: public; Owner: jdr
--

CREATE TABLE public.race_ability_modifier (
    id integer NOT NULL,
    ability character varying(255) DEFAULT NULL::character varying,
    value integer NOT NULL,
    choice_key character varying(80) DEFAULT NULL::character varying,
    race_id integer NOT NULL
);


ALTER TABLE public.race_ability_modifier OWNER TO jdr;

--
-- Name: race_ability_modifier_id_seq; Type: SEQUENCE; Schema: public; Owner: jdr
--

ALTER TABLE public.race_ability_modifier ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.race_ability_modifier_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: character_race character_race_pkey; Type: CONSTRAINT; Schema: public; Owner: jdr
--

ALTER TABLE ONLY public.character_race
    ADD CONSTRAINT character_race_pkey PRIMARY KEY (id);


--
-- Name: race_ability_modifier race_ability_modifier_pkey; Type: CONSTRAINT; Schema: public; Owner: jdr
--

ALTER TABLE ONLY public.race_ability_modifier
    ADD CONSTRAINT race_ability_modifier_pkey PRIMARY KEY (id);


--
-- Name: idx_cd93af371c11a04b; Type: INDEX; Schema: public; Owner: jdr
--

CREATE INDEX idx_cd93af371c11a04b ON public.character_race USING btree (parent_race_id);


--
-- Name: idx_d969a5376e59d40d; Type: INDEX; Schema: public; Owner: jdr
--

CREATE INDEX idx_d969a5376e59d40d ON public.race_ability_modifier USING btree (race_id);


--
-- Name: uniq_character_race_slug; Type: INDEX; Schema: public; Owner: jdr
--

CREATE UNIQUE INDEX uniq_character_race_slug ON public.character_race USING btree (slug);


--
-- Name: uniq_race_ability_choice_key; Type: INDEX; Schema: public; Owner: jdr
--

CREATE UNIQUE INDEX uniq_race_ability_choice_key ON public.race_ability_modifier USING btree (race_id, choice_key);


--
-- Name: character_race fk_cd93af371c11a04b; Type: FK CONSTRAINT; Schema: public; Owner: jdr
--

ALTER TABLE ONLY public.character_race
    ADD CONSTRAINT fk_cd93af371c11a04b FOREIGN KEY (parent_race_id) REFERENCES public.character_race(id) ON DELETE SET NULL;


--
-- Name: race_ability_modifier fk_d969a5376e59d40d; Type: FK CONSTRAINT; Schema: public; Owner: jdr
--

ALTER TABLE ONLY public.race_ability_modifier
    ADD CONSTRAINT fk_d969a5376e59d40d FOREIGN KEY (race_id) REFERENCES public.character_race(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict 8DedF4PA4nrjDovOLzlxSRLdl5qbXXejXveya9K1PaQd1Xsm1cHkmz2OPJzmVq9

