<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260906113954 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE character_wallet (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, copper_pieces INT DEFAULT 0 NOT NULL, silver_pieces INT DEFAULT 0 NOT NULL, electrum_pieces INT DEFAULT 0 NOT NULL, gold_pieces INT DEFAULT 0 NOT NULL, platinum_pieces INT DEFAULT 0 NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, character_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql(
    'INSERT INTO character_wallet (
        character_id,
        copper_pieces,
        silver_pieces,
        electrum_pieces,
        gold_pieces,
        platinum_pieces,
        updated_at
    )
    SELECT
        id,
        0,
        0,
        0,
        0,
        0,
        CURRENT_TIMESTAMP
    FROM "character"'
);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_DF2A518C1136BE75 ON character_wallet (character_id)');
        $this->addSql('ALTER TABLE character_wallet ADD CONSTRAINT FK_DF2A518C1136BE75 FOREIGN KEY (character_id) REFERENCES character (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE character_wallet DROP CONSTRAINT FK_DF2A518C1136BE75');
        $this->addSql('DROP TABLE character_wallet');
    }
}
