<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260903165003 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE campaign (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(80) NOT NULL, name VARCHAR(150) NOT NULL, owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1F1512DD7E3C61F9 ON campaign (owner_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_campaign_owner_slug ON campaign (owner_id, slug)');
        $this->addSql('CREATE TABLE character (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(80) NOT NULL, name VARCHAR(100) NOT NULL, player_name VARCHAR(100) DEFAULT NULL, type VARCHAR(20) NOT NULL, definition JSON NOT NULL, campaign_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_937AB034F639F774 ON character (campaign_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_character_campaign_slug ON character (campaign_id, slug)');
        $this->addSql('CREATE TABLE character_session_state (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, access_token VARCHAR(64) NOT NULL, state JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, game_session_id INT NOT NULL, character_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4C5FD754B6A2DD68 ON character_session_state (access_token)');
        $this->addSql('CREATE INDEX IDX_4C5FD7548FE32B32 ON character_session_state (game_session_id)');
        $this->addSql('CREATE INDEX IDX_4C5FD7541136BE75 ON character_session_state (character_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_session_character ON character_session_state (game_session_id, character_id)');
        $this->addSql('CREATE TABLE game_session (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(80) NOT NULL, name VARCHAR(150) NOT NULL, status VARCHAR(20) NOT NULL, display_state JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, campaign_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4586AAFBF639F774 ON game_session (campaign_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_session_campaign_slug ON game_session (campaign_id, slug)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('ALTER TABLE campaign ADD CONSTRAINT FK_1F1512DD7E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE character ADD CONSTRAINT FK_937AB034F639F774 FOREIGN KEY (campaign_id) REFERENCES campaign (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE character_session_state ADD CONSTRAINT FK_4C5FD7548FE32B32 FOREIGN KEY (game_session_id) REFERENCES game_session (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE character_session_state ADD CONSTRAINT FK_4C5FD7541136BE75 FOREIGN KEY (character_id) REFERENCES character (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE game_session ADD CONSTRAINT FK_4586AAFBF639F774 FOREIGN KEY (campaign_id) REFERENCES campaign (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE campaign DROP CONSTRAINT FK_1F1512DD7E3C61F9');
        $this->addSql('ALTER TABLE character DROP CONSTRAINT FK_937AB034F639F774');
        $this->addSql('ALTER TABLE character_session_state DROP CONSTRAINT FK_4C5FD7548FE32B32');
        $this->addSql('ALTER TABLE character_session_state DROP CONSTRAINT FK_4C5FD7541136BE75');
        $this->addSql('ALTER TABLE game_session DROP CONSTRAINT FK_4586AAFBF639F774');
        $this->addSql('DROP TABLE campaign');
        $this->addSql('DROP TABLE character');
        $this->addSql('DROP TABLE character_session_state');
        $this->addSql('DROP TABLE game_session');
        $this->addSql('DROP TABLE "user"');
    }
}
