<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260906154121 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE character_ability_score (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ability VARCHAR(20) NOT NULL, base_value INT NOT NULL, maximum_value INT DEFAULT 20 NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, character_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql(
    <<<'SQL'
        INSERT INTO character_ability_score (
            character_id,
            ability,
            base_value,
            maximum_value,
            updated_at
        )
        SELECT
            character_data.id,
            ability_data.ability,
            10,
            20,
            CURRENT_TIMESTAMP
        FROM "character" AS character_data
        CROSS JOIN (
            VALUES
                ('strength'),
                ('dexterity'),
                ('constitution'),
                ('intelligence'),
                ('wisdom'),
                ('charisma')
        ) AS ability_data(ability)
    SQL,
);
        $this->addSql('CREATE INDEX IDX_64C201F71136BE75 ON character_ability_score (character_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_character_ability ON character_ability_score (character_id, ability)');
        $this->addSql('ALTER TABLE character_ability_score ADD CONSTRAINT FK_64C201F71136BE75 FOREIGN KEY (character_id) REFERENCES character (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE character_ability_score DROP CONSTRAINT FK_64C201F71136BE75');
        $this->addSql('DROP TABLE character_ability_score');
    }
}
