<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260913151938 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE weather (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, key VARCHAR(80) NOT NULL, label VARCHAR(120) NOT NULL, image_url VARCHAR(255) DEFAULT NULL, alt VARCHAR(255) DEFAULT NULL, system BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, campaign_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4CD0D36EF639F774 ON weather (campaign_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_weather_system_key ON weather (system, key)');
        $this->addSql('CREATE UNIQUE INDEX uniq_weather_campaign_key ON weather (campaign_id, key)');
        $this->addSql('ALTER TABLE weather ADD CONSTRAINT FK_4CD0D36EF639F774 FOREIGN KEY (campaign_id) REFERENCES campaign (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE game_session ADD show_weather BOOLEAN DEFAULT TRUE NOT NULL');
        $this->addSql('ALTER TABLE game_session ADD moon_phase VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE game_session ADD show_moon_phase BOOLEAN DEFAULT FALSE NOT NULL');
        $this->addSql('ALTER TABLE game_session ADD weather_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE game_session ADD CONSTRAINT FK_4586AAFB8CE675E FOREIGN KEY (weather_id) REFERENCES weather (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_4586AAFB8CE675E ON game_session (weather_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE weather DROP CONSTRAINT FK_4CD0D36EF639F774');
        $this->addSql('DROP TABLE weather');
        $this->addSql('ALTER TABLE game_session DROP CONSTRAINT FK_4586AAFB8CE675E');
        $this->addSql('DROP INDEX IDX_4586AAFB8CE675E');
        $this->addSql('ALTER TABLE game_session DROP show_weather');
        $this->addSql('ALTER TABLE game_session DROP moon_phase');
        $this->addSql('ALTER TABLE game_session DROP show_moon_phase');
        $this->addSql('ALTER TABLE game_session DROP weather_id');
    }
}
