<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260910171955 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add GM-only progression stage descriptions and adjustment reference rules.';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE progression_adjustment_rule (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, direction VARCHAR(4) NOT NULL, trigger_type VARCHAR(120) DEFAULT NULL, description TEXT NOT NULL, adjustment_label VARCHAR(255) NOT NULL, display_order INT DEFAULT 0 NOT NULL, progression_definition_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_726A9760717CB52 ON progression_adjustment_rule (progression_definition_id)');
        $this->addSql('ALTER TABLE progression_adjustment_rule ADD CONSTRAINT FK_726A9760717CB52 FOREIGN KEY (progression_definition_id) REFERENCES progression_definition (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE progression_stage ADD description TEXT DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE progression_adjustment_rule DROP CONSTRAINT FK_726A9760717CB52');
        $this->addSql('DROP TABLE progression_adjustment_rule');
        $this->addSql('ALTER TABLE progression_stage DROP description');
    }
}
