<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260909113601 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE character_progression (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, character_id INT NOT NULL, progression_definition_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D1D8FADF1136BE75 ON character_progression (character_id)');
        $this->addSql('CREATE INDEX IDX_D1D8FADF717CB52 ON character_progression (progression_definition_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_character_progression ON character_progression (character_id, progression_definition_id)');
        $this->addSql('ALTER TABLE character_progression ADD CONSTRAINT FK_D1D8FADF1136BE75 FOREIGN KEY (character_id) REFERENCES character (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE character_progression ADD CONSTRAINT FK_D1D8FADF717CB52 FOREIGN KEY (progression_definition_id) REFERENCES progression_definition (id) ON DELETE RESTRICT NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE character_progression DROP CONSTRAINT FK_D1D8FADF1136BE75');
        $this->addSql('ALTER TABLE character_progression DROP CONSTRAINT FK_D1D8FADF717CB52');
        $this->addSql('DROP TABLE character_progression');
    }
}
