<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260907002457 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE trackable_resource_rule (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, unlock_level INT NOT NULL, maximum_override INT DEFAULT NULL, resource_definition_id INT NOT NULL, character_class_id INT DEFAULT NULL, character_subclass_id INT DEFAULT NULL, character_race_id INT DEFAULT NULL, feat_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7B7B5A4698F28FD7 ON trackable_resource_rule (resource_definition_id)');
        $this->addSql('CREATE INDEX IDX_7B7B5A46B201E281 ON trackable_resource_rule (character_class_id)');
        $this->addSql('CREATE INDEX IDX_7B7B5A46E5FA1C35 ON trackable_resource_rule (character_subclass_id)');
        $this->addSql('CREATE INDEX IDX_7B7B5A467FC5430 ON trackable_resource_rule (character_race_id)');
        $this->addSql('CREATE INDEX IDX_7B7B5A46F43C4D5C ON trackable_resource_rule (feat_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_class_resource_level ON trackable_resource_rule (character_class_id, resource_definition_id, unlock_level)');
        $this->addSql('CREATE UNIQUE INDEX uniq_subclass_resource_level ON trackable_resource_rule (character_subclass_id, resource_definition_id, unlock_level)');
        $this->addSql('CREATE UNIQUE INDEX uniq_race_resource_level ON trackable_resource_rule (character_race_id, resource_definition_id, unlock_level)');
        $this->addSql('CREATE UNIQUE INDEX uniq_feat_resource_level ON trackable_resource_rule (feat_id, resource_definition_id, unlock_level)');
        $this->addSql('ALTER TABLE trackable_resource_rule ADD CONSTRAINT FK_7B7B5A4698F28FD7 FOREIGN KEY (resource_definition_id) REFERENCES trackable_resource_definition (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE trackable_resource_rule ADD CONSTRAINT FK_7B7B5A46B201E281 FOREIGN KEY (character_class_id) REFERENCES character_class (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE trackable_resource_rule ADD CONSTRAINT FK_7B7B5A46E5FA1C35 FOREIGN KEY (character_subclass_id) REFERENCES character_subclass (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE trackable_resource_rule ADD CONSTRAINT FK_7B7B5A467FC5430 FOREIGN KEY (character_race_id) REFERENCES character_race (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE trackable_resource_rule ADD CONSTRAINT FK_7B7B5A46F43C4D5C FOREIGN KEY (feat_id) REFERENCES feat (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE trackable_resource_rule DROP CONSTRAINT FK_7B7B5A4698F28FD7');
        $this->addSql('ALTER TABLE trackable_resource_rule DROP CONSTRAINT FK_7B7B5A46B201E281');
        $this->addSql('ALTER TABLE trackable_resource_rule DROP CONSTRAINT FK_7B7B5A46E5FA1C35');
        $this->addSql('ALTER TABLE trackable_resource_rule DROP CONSTRAINT FK_7B7B5A467FC5430');
        $this->addSql('ALTER TABLE trackable_resource_rule DROP CONSTRAINT FK_7B7B5A46F43C4D5C');
        $this->addSql('DROP TABLE trackable_resource_rule');
    }
}
