<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260914174026 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE character_action_class_rule (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, unlock_level INT NOT NULL, action_definition_id INT NOT NULL, character_class_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_96DC1850EAECFB0D ON character_action_class_rule (action_definition_id)');
        $this->addSql('CREATE INDEX IDX_96DC1850B201E281 ON character_action_class_rule (character_class_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_character_action_class ON character_action_class_rule (action_definition_id, character_class_id)');
        $this->addSql('CREATE TABLE character_action_definition (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(100) NOT NULL, name VARCHAR(150) NOT NULL, description TEXT DEFAULT NULL, handler_type VARCHAR(255) NOT NULL, requires_preparation BOOLEAN NOT NULL, active BOOLEAN DEFAULT true NOT NULL, custom BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_character_action_slug ON character_action_definition (slug)');
        $this->addSql('ALTER TABLE character_action_class_rule ADD CONSTRAINT FK_96DC1850EAECFB0D FOREIGN KEY (action_definition_id) REFERENCES character_action_definition (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE character_action_class_rule ADD CONSTRAINT FK_96DC1850B201E281 FOREIGN KEY (character_class_id) REFERENCES character_class (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE character_action_class_rule DROP CONSTRAINT FK_96DC1850EAECFB0D');
        $this->addSql('ALTER TABLE character_action_class_rule DROP CONSTRAINT FK_96DC1850B201E281');
        $this->addSql('DROP TABLE character_action_class_rule');
        $this->addSql('DROP TABLE character_action_definition');
    }
}
