<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260907160804 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE character_feature_rule (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, unlock_level INT NOT NULL, display_order INT DEFAULT 0 NOT NULL, feature_definition_id INT NOT NULL, character_class_id INT DEFAULT NULL, character_subclass_id INT DEFAULT NULL, character_race_id INT DEFAULT NULL, feat_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CB96A6D6B8A00E59 ON character_feature_rule (feature_definition_id)');
        $this->addSql('CREATE INDEX IDX_CB96A6D6B201E281 ON character_feature_rule (character_class_id)');
        $this->addSql('CREATE INDEX IDX_CB96A6D6E5FA1C35 ON character_feature_rule (character_subclass_id)');
        $this->addSql('CREATE INDEX IDX_CB96A6D67FC5430 ON character_feature_rule (character_race_id)');
        $this->addSql('CREATE INDEX IDX_CB96A6D6F43C4D5C ON character_feature_rule (feat_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_class_feature_level ON character_feature_rule (character_class_id, feature_definition_id, unlock_level)');
        $this->addSql('CREATE UNIQUE INDEX uniq_subclass_feature_level ON character_feature_rule (character_subclass_id, feature_definition_id, unlock_level)');
        $this->addSql('CREATE UNIQUE INDEX uniq_race_feature_level ON character_feature_rule (character_race_id, feature_definition_id, unlock_level)');
        $this->addSql('CREATE UNIQUE INDEX uniq_feat_feature_level ON character_feature_rule (feat_id, feature_definition_id, unlock_level)');
        $this->addSql('ALTER TABLE character_feature_rule ADD CONSTRAINT FK_CB96A6D6B8A00E59 FOREIGN KEY (feature_definition_id) REFERENCES character_feature_definition (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE character_feature_rule ADD CONSTRAINT FK_CB96A6D6B201E281 FOREIGN KEY (character_class_id) REFERENCES character_class (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE character_feature_rule ADD CONSTRAINT FK_CB96A6D6E5FA1C35 FOREIGN KEY (character_subclass_id) REFERENCES character_subclass (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE character_feature_rule ADD CONSTRAINT FK_CB96A6D67FC5430 FOREIGN KEY (character_race_id) REFERENCES character_race (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE character_feature_rule ADD CONSTRAINT FK_CB96A6D6F43C4D5C FOREIGN KEY (feat_id) REFERENCES feat (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE character_feature_rule DROP CONSTRAINT FK_CB96A6D6B8A00E59');
        $this->addSql('ALTER TABLE character_feature_rule DROP CONSTRAINT FK_CB96A6D6B201E281');
        $this->addSql('ALTER TABLE character_feature_rule DROP CONSTRAINT FK_CB96A6D6E5FA1C35');
        $this->addSql('ALTER TABLE character_feature_rule DROP CONSTRAINT FK_CB96A6D67FC5430');
        $this->addSql('ALTER TABLE character_feature_rule DROP CONSTRAINT FK_CB96A6D6F43C4D5C');
        $this->addSql('DROP TABLE character_feature_rule');
    }
}
