<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260906233649 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE character_class_level_rule (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, level INT NOT NULL, advancement_choice VARCHAR(255) NOT NULL, notes TEXT DEFAULT NULL, character_class_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2FDDA57BB201E281 ON character_class_level_rule (character_class_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_character_class_level_rule ON character_class_level_rule (character_class_id, level)');
        $this->addSql('ALTER TABLE character_class_level_rule ADD CONSTRAINT FK_2FDDA57BB201E281 FOREIGN KEY (character_class_id) REFERENCES character_class (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE character_class_level_rule DROP CONSTRAINT FK_2FDDA57BB201E281');
        $this->addSql('DROP TABLE character_class_level_rule');
    }
}
