<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260909095152 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE progression_definition (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(80) NOT NULL, name VARCHAR(120) NOT NULL, description TEXT DEFAULT NULL, minimum_value INT NOT NULL, maximum_value INT DEFAULT NULL, accent_color VARCHAR(20) DEFAULT NULL, gain_label VARCHAR(80) DEFAULT NULL, spend_label VARCHAR(80) DEFAULT NULL, custom BOOLEAN DEFAULT false NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_progression_definition_slug ON progression_definition (slug)');
        $this->addSql('CREATE TABLE progression_stage (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, label VARCHAR(120) NOT NULL, minimum_value INT NOT NULL, maximum_value INT DEFAULT NULL, icon_url VARCHAR(255) DEFAULT NULL, display_order INT DEFAULT 0 NOT NULL, progression_definition_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C1D8BE9B717CB52 ON progression_stage (progression_definition_id)');
        $this->addSql('ALTER TABLE progression_stage ADD CONSTRAINT FK_C1D8BE9B717CB52 FOREIGN KEY (progression_definition_id) REFERENCES progression_definition (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE progression_stage DROP CONSTRAINT FK_C1D8BE9B717CB52');
        $this->addSql('DROP TABLE progression_definition');
        $this->addSql('DROP TABLE progression_stage');
    }
}
