<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260907001908 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE trackable_resource_definition (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(100) NOT NULL, name VARCHAR(150) NOT NULL, description TEXT DEFAULT NULL, recharge_type VARCHAR(255) NOT NULL, maximum_type VARCHAR(255) NOT NULL, base_maximum INT NOT NULL, multiplier INT NOT NULL, minimum_maximum INT NOT NULL, scaling_ability VARCHAR(255) DEFAULT NULL, custom BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_trackable_resource_slug ON trackable_resource_definition (slug)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE trackable_resource_definition');
    }
}
