<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260903204704 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE rest_request (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(20) NOT NULL, status VARCHAR(20) NOT NULL, requested_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, resolved_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, character_session_state_id INT NOT NULL, resolved_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8EBFEB738595CAD ON rest_request (character_session_state_id)');
        $this->addSql('CREATE INDEX IDX_8EBFEB76713A32B ON rest_request (resolved_by_id)');
        $this->addSql('ALTER TABLE rest_request ADD CONSTRAINT FK_8EBFEB738595CAD FOREIGN KEY (character_session_state_id) REFERENCES character_session_state (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE rest_request ADD CONSTRAINT FK_8EBFEB76713A32B FOREIGN KEY (resolved_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE rest_request DROP CONSTRAINT FK_8EBFEB738595CAD');
        $this->addSql('ALTER TABLE rest_request DROP CONSTRAINT FK_8EBFEB76713A32B');
        $this->addSql('DROP TABLE rest_request');
    }
}
