<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260906163029 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE character_magic_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantity INT DEFAULT 1 NOT NULL, current_charges INT DEFAULT NULL, attuned BOOLEAN NOT NULL, equipped BOOLEAN NOT NULL, notes TEXT DEFAULT NULL, acquired_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, character_id INT NOT NULL, magic_item_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F37BB4AF1136BE75 ON character_magic_item (character_id)');
        $this->addSql('CREATE INDEX IDX_F37BB4AFC7AAA1EF ON character_magic_item (magic_item_id)');
        $this->addSql('CREATE TABLE magic_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(150) NOT NULL, description TEXT DEFAULT NULL, rarity VARCHAR(20) NOT NULL, requires_attunement BOOLEAN NOT NULL, maximum_charges INT DEFAULT NULL, recharge_type VARCHAR(20) NOT NULL, recharge_formula VARCHAR(50) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, campaign_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_42F70D29F639F774 ON magic_item (campaign_id)');
        $this->addSql('CREATE TABLE magic_item_ability_effect (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ability VARCHAR(20) NOT NULL, operation VARCHAR(30) NOT NULL, value INT NOT NULL, score_cap INT DEFAULT NULL, maximum_increase INT DEFAULT 0 NOT NULL, magic_item_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8EEFC6BDC7AAA1EF ON magic_item_ability_effect (magic_item_id)');
        $this->addSql('ALTER TABLE character_magic_item ADD CONSTRAINT FK_F37BB4AF1136BE75 FOREIGN KEY (character_id) REFERENCES character (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE character_magic_item ADD CONSTRAINT FK_F37BB4AFC7AAA1EF FOREIGN KEY (magic_item_id) REFERENCES magic_item (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE magic_item ADD CONSTRAINT FK_42F70D29F639F774 FOREIGN KEY (campaign_id) REFERENCES campaign (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE magic_item_ability_effect ADD CONSTRAINT FK_8EEFC6BDC7AAA1EF FOREIGN KEY (magic_item_id) REFERENCES magic_item (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE character_magic_item DROP CONSTRAINT FK_F37BB4AF1136BE75');
        $this->addSql('ALTER TABLE character_magic_item DROP CONSTRAINT FK_F37BB4AFC7AAA1EF');
        $this->addSql('ALTER TABLE magic_item DROP CONSTRAINT FK_42F70D29F639F774');
        $this->addSql('ALTER TABLE magic_item_ability_effect DROP CONSTRAINT FK_8EEFC6BDC7AAA1EF');
        $this->addSql('DROP TABLE character_magic_item');
        $this->addSql('DROP TABLE magic_item');
        $this->addSql('DROP TABLE magic_item_ability_effect');
    }
}
