<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260907155605 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE character_feature_definition (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(100) NOT NULL, name VARCHAR(150) NOT NULL, description TEXT DEFAULT NULL, activation_type VARCHAR(255) NOT NULL, visible BOOLEAN DEFAULT true NOT NULL, custom BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, resource_definition_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_12EBB15998F28FD7 ON character_feature_definition (resource_definition_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_character_feature_slug ON character_feature_definition (slug)');
        $this->addSql('ALTER TABLE character_feature_definition ADD CONSTRAINT FK_12EBB15998F28FD7 FOREIGN KEY (resource_definition_id) REFERENCES trackable_resource_definition (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE character_feature_definition DROP CONSTRAINT FK_12EBB15998F28FD7');
        $this->addSql('DROP TABLE character_feature_definition');
    }
}
