<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260906201605 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE character_class (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(80) NOT NULL, name VARCHAR(120) NOT NULL, hit_die INT NOT NULL, subclass_selection_level INT NOT NULL, spellcasting_progression VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, custom BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_character_class_slug ON character_class (slug)');
        $this->addSql('CREATE TABLE character_class_level (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, class_level INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, character_id INT NOT NULL, character_class_id INT NOT NULL, subclass_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_785747891136BE75 ON character_class_level (character_id)');
        $this->addSql('CREATE INDEX IDX_78574789B201E281 ON character_class_level (character_class_id)');
        $this->addSql('CREATE INDEX IDX_78574789E190B699 ON character_class_level (subclass_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_character_class_level ON character_class_level (character_id, character_class_id)');
        $this->addSql('CREATE TABLE character_feat (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, chosen_ability VARCHAR(255) DEFAULT NULL, acquired_at_level INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, character_id INT NOT NULL, feat_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4D6785531136BE75 ON character_feat (character_id)');
        $this->addSql('CREATE INDEX IDX_4D678553F43C4D5C ON character_feat (feat_id)');
        $this->addSql('CREATE TABLE character_race (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(80) NOT NULL, name VARCHAR(120) NOT NULL, description TEXT DEFAULT NULL, custom BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, parent_race_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CD93AF371C11A04B ON character_race (parent_race_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_character_race_slug ON character_race (slug)');
        $this->addSql('CREATE TABLE character_race_ability_choice (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ability VARCHAR(255) NOT NULL, character_id INT NOT NULL, modifier_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_235599291136BE75 ON character_race_ability_choice (character_id)');
        $this->addSql('CREATE INDEX IDX_23559929D079F553 ON character_race_ability_choice (modifier_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_character_race_modifier_choice ON character_race_ability_choice (character_id, modifier_id)');
        $this->addSql('CREATE TABLE character_subclass (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(80) NOT NULL, name VARCHAR(120) NOT NULL, spellcasting_progression VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, custom BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, character_class_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CFF91FD4B201E281 ON character_subclass (character_class_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_subclass_class_slug ON character_subclass (character_class_id, slug)');
        $this->addSql('CREATE TABLE feat (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(80) NOT NULL, name VARCHAR(120) NOT NULL, description TEXT DEFAULT NULL, repeatable BOOLEAN NOT NULL, requires_ability_choice BOOLEAN NOT NULL, chosen_ability_increase INT NOT NULL, custom BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_feat_slug ON feat (slug)');
        $this->addSql('CREATE TABLE race_ability_modifier (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ability VARCHAR(255) DEFAULT NULL, value INT NOT NULL, choice_key VARCHAR(80) DEFAULT NULL, race_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D969A5376E59D40D ON race_ability_modifier (race_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_race_ability_choice_key ON race_ability_modifier (race_id, choice_key)');
        $this->addSql('ALTER TABLE character_class_level ADD CONSTRAINT FK_785747891136BE75 FOREIGN KEY (character_id) REFERENCES character (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE character_class_level ADD CONSTRAINT FK_78574789B201E281 FOREIGN KEY (character_class_id) REFERENCES character_class (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE character_class_level ADD CONSTRAINT FK_78574789E190B699 FOREIGN KEY (subclass_id) REFERENCES character_subclass (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE character_feat ADD CONSTRAINT FK_4D6785531136BE75 FOREIGN KEY (character_id) REFERENCES character (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE character_feat ADD CONSTRAINT FK_4D678553F43C4D5C FOREIGN KEY (feat_id) REFERENCES feat (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE character_race ADD CONSTRAINT FK_CD93AF371C11A04B FOREIGN KEY (parent_race_id) REFERENCES character_race (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE character_race_ability_choice ADD CONSTRAINT FK_235599291136BE75 FOREIGN KEY (character_id) REFERENCES character (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE character_race_ability_choice ADD CONSTRAINT FK_23559929D079F553 FOREIGN KEY (modifier_id) REFERENCES race_ability_modifier (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE character_subclass ADD CONSTRAINT FK_CFF91FD4B201E281 FOREIGN KEY (character_class_id) REFERENCES character_class (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE race_ability_modifier ADD CONSTRAINT FK_D969A5376E59D40D FOREIGN KEY (race_id) REFERENCES character_race (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "character" ADD race_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE "character" ADD CONSTRAINT FK_937AB0346E59D40D FOREIGN KEY (race_id) REFERENCES character_race (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_937AB0346E59D40D ON "character" (race_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE character_class_level DROP CONSTRAINT FK_785747891136BE75');
        $this->addSql('ALTER TABLE character_class_level DROP CONSTRAINT FK_78574789B201E281');
        $this->addSql('ALTER TABLE character_class_level DROP CONSTRAINT FK_78574789E190B699');
        $this->addSql('ALTER TABLE character_feat DROP CONSTRAINT FK_4D6785531136BE75');
        $this->addSql('ALTER TABLE character_feat DROP CONSTRAINT FK_4D678553F43C4D5C');
        $this->addSql('ALTER TABLE character_race DROP CONSTRAINT FK_CD93AF371C11A04B');
        $this->addSql('ALTER TABLE character_race_ability_choice DROP CONSTRAINT FK_235599291136BE75');
        $this->addSql('ALTER TABLE character_race_ability_choice DROP CONSTRAINT FK_23559929D079F553');
        $this->addSql('ALTER TABLE character_subclass DROP CONSTRAINT FK_CFF91FD4B201E281');
        $this->addSql('ALTER TABLE race_ability_modifier DROP CONSTRAINT FK_D969A5376E59D40D');
        $this->addSql('DROP TABLE character_class');
        $this->addSql('DROP TABLE character_class_level');
        $this->addSql('DROP TABLE character_feat');
        $this->addSql('DROP TABLE character_race');
        $this->addSql('DROP TABLE character_race_ability_choice');
        $this->addSql('DROP TABLE character_subclass');
        $this->addSql('DROP TABLE feat');
        $this->addSql('DROP TABLE race_ability_modifier');
        $this->addSql('ALTER TABLE character DROP CONSTRAINT FK_937AB0346E59D40D');
        $this->addSql('DROP INDEX IDX_937AB0346E59D40D');
        $this->addSql('ALTER TABLE character DROP race_id');
    }
}
