<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260905231543 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE campaign_figure (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(120) NOT NULL, encounter_status VARCHAR(20) NOT NULL, character_type VARCHAR(10) NOT NULL, life_status VARCHAR(20) NOT NULL, description VARCHAR(255) NOT NULL, death_label VARCHAR(80) DEFAULT NULL, publication_status VARCHAR(20) NOT NULL, display_order INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, campaign_id INT NOT NULL, portrait_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F214CAD7F639F774 ON campaign_figure (campaign_id)');
        $this->addSql('CREATE INDEX IDX_F214CAD71226EBF3 ON campaign_figure (portrait_id)');
        $this->addSql('CREATE TABLE tip (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, label VARCHAR(100) NOT NULL, text TEXT NOT NULL, category VARCHAR(20) NOT NULL, display_order INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, status VARCHAR(20) NOT NULL, campaign_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4883B84CF639F774 ON tip (campaign_id)');
        $this->addSql('ALTER TABLE campaign_figure ADD CONSTRAINT FK_F214CAD7F639F774 FOREIGN KEY (campaign_id) REFERENCES campaign (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE campaign_figure ADD CONSTRAINT FK_F214CAD71226EBF3 FOREIGN KEY (portrait_id) REFERENCES media (id)');
        $this->addSql('ALTER TABLE tip ADD CONSTRAINT FK_4883B84CF639F774 FOREIGN KEY (campaign_id) REFERENCES campaign (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE campaign_figure DROP CONSTRAINT FK_F214CAD7F639F774');
        $this->addSql('ALTER TABLE campaign_figure DROP CONSTRAINT FK_F214CAD71226EBF3');
        $this->addSql('ALTER TABLE tip DROP CONSTRAINT FK_4883B84CF639F774');
        $this->addSql('DROP TABLE campaign_figure');
        $this->addSql('DROP TABLE tip');
    }
}
