<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260906221755 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE character_ability_adjustment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ability VARCHAR(255) NOT NULL, operation VARCHAR(255) NOT NULL, value INT NOT NULL, source VARCHAR(255) NOT NULL, label VARCHAR(150) NOT NULL, description TEXT DEFAULT NULL, acquired_at_level INT DEFAULT NULL, display_order INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, character_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2FD68EDE1136BE75 ON character_ability_adjustment (character_id)');
        $this->addSql('ALTER TABLE character_ability_adjustment ADD CONSTRAINT FK_2FD68EDE1136BE75 FOREIGN KEY (character_id) REFERENCES character (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE character_ability_adjustment DROP CONSTRAINT FK_2FD68EDE1136BE75');
        $this->addSql('DROP TABLE character_ability_adjustment');
    }
}
