<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260914222831 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE character_active_effect (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, effect_type VARCHAR(50) NOT NULL, amount INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, target_character_id INT NOT NULL, source_character_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1DE8F59CF1646D24 ON character_active_effect (target_character_id)');
        $this->addSql('CREATE INDEX IDX_1DE8F59CC7DC62CD ON character_active_effect (source_character_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_character_active_effect_target_type ON character_active_effect (target_character_id, effect_type)');
        $this->addSql('ALTER TABLE character_active_effect ADD CONSTRAINT FK_1DE8F59CF1646D24 FOREIGN KEY (target_character_id) REFERENCES character (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE character_active_effect ADD CONSTRAINT FK_1DE8F59CC7DC62CD FOREIGN KEY (source_character_id) REFERENCES character (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE character_active_effect DROP CONSTRAINT FK_1DE8F59CF1646D24');
        $this->addSql('ALTER TABLE character_active_effect DROP CONSTRAINT FK_1DE8F59CC7DC62CD');
        $this->addSql('DROP TABLE character_active_effect');
    }
}
