<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260905000215 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE quest (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(150) NOT NULL, objective TEXT NOT NULL, category VARCHAR(80) NOT NULL, status VARCHAR(20) NOT NULL, display_order INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, campaign_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4317F817F639F774 ON quest (campaign_id)');
        $this->addSql('ALTER TABLE quest ADD CONSTRAINT FK_4317F817F639F774 FOREIGN KEY (campaign_id) REFERENCES campaign (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE quest DROP CONSTRAINT FK_4317F817F639F774');
        $this->addSql('DROP TABLE quest');
    }
}
